Repository vmware/clarity, pull requests merged in 2018-02, with the labels that each got.

#1965 [NG] Update Build to ng-packagr 2.0.0 (latest, stable)
  package-lock.json
  package.json
Labels: Build/Travis, Chore

#1960 [NG] get unit tests working with Firefox
  karma.conf.js
  package-lock.json
  package.json
  src/clr-angular/typography/typography.spec.ts
  src/clr-angular/utils/focus-trap/focus-trap.directive.spec.ts
  src/clr-angular/utils/virtual-scroll/dom-helpers.spec.ts
  src/clr-angular/utils/virtual-scroll/virtual-for-of.spec.ts
  tests/tests.entry.ts
  tests/tests.helpers.ts
Labels: Browser: Firefox, Build/Travis, In Review

#1908 [CORE] Fixes orphaned webserver for gemini tests.
  scripts/docker-cdc.js
Labels: Bug, Docker, Gemini

#1977 [NG] Safari unit testing
  package-lock.json
  package.json
  src/clr-angular/utils/virtual-scroll/virtual-for-of.spec.ts
  tests/tests.helpers.ts
Labels: Browser: Safari, Build/Travis, Chore, In Review

#2009 [CORE] Fix NgModule Imports in README
  README.md
Labels: In Review

#1978 [CORE] setup saucelabs with travis, fix code coverage
  .gemini.conf.yml
  .gitignore
  .travis.yml
  README.md
  karma.conf.js
  package-lock.json
  package.json
  webpack.test.config.js
Labels: Build/Travis, In Review

#2015 [NG] fix issues for changes in angular cli
  src/app/alert/alert.demo.module.ts
  src/app/app.routing.ts
  src/app/badges/badges.demo.module.ts
  src/app/button-group/button-group.demo.module.ts
  src/app/buttons/buttons.demo.module.ts
  src/app/card/card.demo.module.ts
  src/app/checkboxes/checkboxes.demo.module.ts
  src/app/code/code-highlight.demo.module.ts
  src/app/color/color.demo.module.ts
  src/app/datagrid/datagrid.demo.module.ts
  src/app/dropdown/dropdown.demo.module.ts
  src/app/forms-deprecated/forms.demo.module.ts
  src/app/grid/grid.demo.module.ts
  src/app/iconography/iconography.demo.module.ts
  src/app/images/images.demo.module.ts
  src/app/input-fields/input-fields.demo.module.ts
  src/app/labels/labels.demo.module.ts
  src/app/layout/layout.demo.module.ts
  src/app/lists/lists.demo.module.ts
  src/app/login/login.demo.module.ts
  src/app/modal/modal.demo.module.ts
  src/app/nav/nav.demo.module.ts
  src/app/progress-bars/progress-bars.demo.module.ts
  src/app/radios/radios.demo.module.ts
  src/app/selects/selects.demo.module.ts
  src/app/signpost/signpost.demo.module.ts
  src/app/spinners/spinners.demo.module.ts
  src/app/stack-view/stack-view.demo.module.ts
  src/app/tables/tables.demo.module.ts
  src/app/tabs/tabs.demo.module.ts
  src/app/toggles/toggles.demo.module.ts
  src/app/tooltips/tooltips.demo.module.ts
  src/app/tree-view/tree-view.demo.module.ts
  src/app/typography/typography.demo.module.ts
  src/app/vertical-nav/vertical-nav.demo.module.ts
  src/app/virtual-scroll/virtual-scroll.demo.module.ts
  src/app/wizard/wizard.demo.module.ts
  webpack.config.js
Labels: Dependency Regression, In Review
