Repository vmware/clarity, pull requests merged in 2018-03, with the labels that each got.

#2012 [ui] fix overlapping clr-icons when inside header dropdown (#1957)
  gemini/screens/navigation/header-types/header-dropdown/chrome.png
  gemini/tests/set3/navigation.js
  src/app/nav/header-types.demo.html
  src/app/nav/header-types.ts
  src/clr-angular/layout/nav/_header.clarity.scss
Labels: In Review

#2042 [Docs] Minor typo and mention new website branch
  latest/README.md
  latest/src/app/documentation/demos/datagrid/datagrid.demo.html
  v0.10/README.md
  v0.10/src/app/documentation/demos/datagrid/datagrid.demo.html
Labels: In Review

#2047 [NG] Remove @private annotation
  src/clr-angular/utils/host-wrapping/host-wrapping.module.ts
Labels: Build/Travis, In Review

#2049 [ux] increase color contrast ratio in buttons to be accessible (#1939)
  gemini/screens/buttons/button-sizes/.btn-success.btn-block/default/chrome.png
  gemini/screens/buttons/button-sizes/.btn-success.btn-sm/default/chrome.png
  gemini/screens/buttons/button-sizes/.btn-success/default/chrome.png
  gemini/screens/buttons/button-states/.btn-success-outline/default/chrome.png
  gemini/screens/buttons/button-states/.btn-success/default/chrome.png
  gemini/screens/buttons/icon-buttons/.clr-example/default/chrome.png
  gemini/screens/buttons/real-buttons/.btn-success-outline/default/chrome.png
  gemini/screens/buttons/real-buttons/.btn-success/default/chrome.png
  src/clr-angular/button/_variables.button.scss
  src/clr-angular/color/_variables.color.scss
  src/clr-angular/color/utils/_colors.clarity.scss
  src/clr-angular/color/utils/_helpers.clarity.scss
  src/clr-angular/utils/_maps.clarity.scss
Labels: Accessibility

#2039 Issue/1145 improve datagrid sorting docs
  latest/src/app/documentation/demos/datagrid/sorting/examples.ts
  latest/src/app/documentation/demos/datagrid/sorting/sorting.html
  latest/src/app/documentation/demos/datagrid/sorting/sorting.ts
  package-lock.json
  v0.10/src/app/documentation/demos/datagrid/sorting/examples.ts
  v0.10/src/app/documentation/demos/datagrid/sorting/sorting.html
  v0.10/src/app/documentation/demos/datagrid/sorting/sorting.ts
Labels: In Review

#2025 [ICONS] icon shapes are modularized
  scripts/write-svg-icons.js
  src/clr-icons/clr-icons.spec.ts
  src/clr-icons/shapes/commerce-shapes.ts
  src/clr-icons/shapes/core-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/media-shapes.ts
  src/clr-icons/shapes/social-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
  src/clr-icons/shapes/travel-shapes.ts
  src/ks-app/src/app/app.component.ts
  src/ks-app/src/app/containers/buttons/buttons.component.html
Labels: ClarityIcons, In Review

#2065 [UI] Datepicker Trigger Icon Color
  gemini/screens/datepicker/datepicker/default/chrome.png
  gemini/screens/datepicker/monthpicker/default/chrome.png
  gemini/screens/datepicker/user-input/default/chrome.png
  gemini/screens/datepicker/user-input/trigger-hovered/chrome.png
  gemini/screens/datepicker/yearpicker/default/chrome.png
  src/clr-angular/forms/datepicker/_datepicker.clarity.scss
  src/clr-angular/forms/datepicker/_variables.datepicker.scss
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/utils/_theme.dark.clarity.scss
Labels: ClarityUI, In Review

#2057 [NG] Cal + Year Range Generation Optimizations
  src/clr-angular/forms/datepicker/providers/date-navigation.service.spec.ts
  src/clr-angular/forms/datepicker/providers/date-navigation.service.ts
  src/clr-angular/forms/datepicker/yearpicker.spec.ts
  src/clr-angular/forms/datepicker/yearpicker.ts
Labels: ClarityNG, In Review

#2067 [NG] Unsubscribe from datagrid cell changes sub
  src/clr-angular/data/datagrid/datagrid-row-detail.ts
Labels: ClarityNG

#2074 [NG] Datagrid Selection Bug Fix
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
Labels: ClarityNG

#2090 [UI] Datagrid Action Overflow Fix
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: ClarityUI, In Review

#2097 [NG] Bug Fix for Datepicker in Reactive Forms
  src/app/datepicker/datepicker-in-reactive-forms.html
  src/app/datepicker/datepicker-in-reactive-forms.ts
  src/app/datepicker/datepicker-in-template-driven-forms.ts
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
Labels: ClarityNG, In Review

#2110 [NG] CLDR Delimiter Support
  src/app/datepicker/datepicker-KKJ.ts
  src/app/datepicker/datepicker-hr.ts
  src/app/datepicker/datepicker-locale-data.ts
  src/app/datepicker/datepicker.demo.html
  src/app/datepicker/datepicker.demo.module.ts
  src/app/datepicker/datepicker.demo.routing.ts
  src/app/datepicker/datepicker.demo.ts
  src/clr-angular/forms/datepicker/_datepicker.clarity.scss
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/providers/date-io.service.spec.ts
  src/clr-angular/forms/datepicker/providers/date-io.service.ts
  src/clr-angular/forms/datepicker/utils/constants.ts
Labels: ClarityNG

#2113 [NG] Clean up datagrid footer's flexbox
  gemini/screens/datagrid-compact/datagrid-compact-hide-show-columns/default/chrome.png
  gemini/screens/datagrid/hide-show/click-ok/chrome.png
  gemini/screens/datagrid/hide-show/default/chrome.png
  gemini/screens/datagrid/hide-show/hide-one/chrome.png
  gemini/screens/datagrid/hide-show/toggle-action/chrome.png
  gemini/screens/datagrid/hide-show/toggle-id/chrome.png
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: Bug, ClarityNG

#2073 [CORE] add support for schematics to add Clarity to an Angular project
  npm/clr-angular/package.json
  package-lock.json
  package.json
  packages/schematics/.gitignore
  packages/schematics/README.md
  packages/schematics/package-lock.json
  packages/schematics/package.json
  packages/schematics/src/add/index.ts
  packages/schematics/src/add/index_spec.ts
  packages/schematics/src/add/schema.d.ts
  packages/schematics/src/add/schema.json
  packages/schematics/src/collection.json
  packages/schematics/src/utility/ast-utils.ts
  packages/schematics/src/utility/ast-utils_spec.ts
  packages/schematics/src/utility/change.ts
  packages/schematics/src/utility/config.ts
  packages/schematics/src/utility/find-module.ts
  packages/schematics/src/utility/find-module_spec.ts
  packages/schematics/src/utility/ng-ast-utils.ts
  packages/schematics/src/utility/route-utils.ts
  packages/schematics/src/utility/test/create-app-module.ts
  packages/schematics/src/utility/test/get-file-content.ts
  packages/schematics/src/utility/test/index.ts
  packages/schematics/tsconfig.json
  src/clr-angular/package.json
Labels: Enhancement
