Repository vmware/clarity, pull requests merged in 2018-05, with the labels that each got.

#2231 [NG] add clientRect method to DomAdapter for accessing Element.getBou…
  src/clr-angular/data/datagrid/all.spec.ts
  src/clr-angular/data/datagrid/animation-hack/row-expand-animation.spec.ts
  src/clr-angular/data/datagrid/animation-hack/row-expand-animation.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.model.spec.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-row.spec.ts
  src/clr-angular/data/datagrid/render/body-renderer.spec.ts
  src/clr-angular/data/datagrid/render/body-renderer.ts
  src/clr-angular/data/datagrid/render/column-resizer.spec.ts
  src/clr-angular/data/datagrid/render/column-resizer.ts
  src/clr-angular/data/datagrid/render/header-renderer.spec.ts
  src/clr-angular/data/datagrid/render/header-renderer.ts
  src/clr-angular/data/datagrid/render/main-renderer.ts
  src/clr-angular/data/datagrid/render/row-renderer.spec.ts
  src/clr-angular/data/datagrid/render/table-renderer.spec.ts
  src/clr-angular/utils/dom-adapter/dom-adapter.mock.ts
  src/clr-angular/utils/dom-adapter/dom-adapter.spec.ts
  src/clr-angular/utils/dom-adapter/dom-adapter.ts
Labels: ClarityNG, In Review

#2225 [SCHEMATICS] remove from 0.11 for compatibility
  npm/clr-angular/package.json
  package.json
  packages/schematics/.gitignore
  packages/schematics/README.md
  packages/schematics/package-lock.json
  packages/schematics/package.json
  packages/schematics/src/add/index.ts
  packages/schematics/src/add/index_spec.ts
  packages/schematics/src/add/schema.d.ts
  packages/schematics/src/add/schema.json
  packages/schematics/src/collection.json
  packages/schematics/src/utility/ast-utils.ts
  packages/schematics/src/utility/ast-utils_spec.ts
  packages/schematics/src/utility/change.ts
  packages/schematics/src/utility/config.ts
  packages/schematics/src/utility/find-module.ts
  packages/schematics/src/utility/find-module_spec.ts
  packages/schematics/src/utility/ng-ast-utils.ts
  packages/schematics/src/utility/route-utils.ts
  packages/schematics/src/utility/test/create-app-module.ts
  packages/schematics/src/utility/test/get-file-content.ts
  packages/schematics/src/utility/test/index.ts
  packages/schematics/tsconfig.json
  src/clr-angular/package.json
Labels: In Review, Internal

#2211 [NG] Enable Angular modals and wizards to support aria.
  src/clr-angular/modal/modal.html
Labels: ClarityNG, In Review

#2248 [UI] Dropdown Nested Menu Arrow Alignment Fix
  gemini/screens/dropdown/angular-nested/clicked/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-left/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-right/chrome.png
  gemini/screens/dropdown/default/default/chrome.png
  src/clr-angular/popover/dropdown/_dropdown.clarity.scss
Labels: ClarityUI, In Review

#2249 [ICONS] addition of Vol.11 icons
  gemini/screens/iconography/selection-commerce-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/line/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid/chrome.png
  gemini/screens/tree-view/Tree View Dynamically Generated/default/chrome.png
  src/app/iconography/icon-selection.ts
  src/clr-icons/clr-icons.spec.ts
  src/clr-icons/shapes/all-shapes.ts
  src/clr-icons/shapes/commerce-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/media-shapes.ts
  src/clr-icons/shapes/social-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
  src/clr-icons/shapes/text-edit-shapes.ts
  src/ks-app/package-lock.json
  src/ks-app/src/app/containers/iconography/icon-selection.component.ts
  webpack.icons.config.js
Labels: ClarityIcons, In Review

#2260 [UI] Add a box-shadow to Date Picker
  gemini/screens/datepicker/datepicker/default/chrome.png
  gemini/screens/datepicker/monthpicker/default/chrome.png
  gemini/screens/datepicker/yearpicker/default/chrome.png
  src/clr-angular/forms/datepicker/_datepicker.clarity.scss
  src/clr-angular/popover/dropdown/_variables.dropdown.scss
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/utils/_variables.global.scss
Labels: ClarityUI, In Review

#2232 [NG] *clrIfDragged structural directive
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  src/clr-angular/utils/drag-and-drop/all.spec.ts
  src/clr-angular/utils/drag-and-drop/helpers.spec.ts
  src/clr-angular/utils/drag-and-drop/if-dragged.spec.ts
  src/clr-angular/utils/drag-and-drop/if-dragged.ts
  src/clr-angular/utils/drag-and-drop/index.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.spec.ts
Labels: ClarityNG, In Review

#2270 [UI] Remove z-index from datagrid column handle
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: ClarityUI, In Review

#2271 [CORE] Fix master build
  src/clr-angular/package.json
  webpack.icons.config.js
Labels: Build/Travis

#2273 [UI] Remove z-index from datagrid column handle
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: ClarityUI, In Review

#2230 [ng] new spinner button (#1488)
  gemini/tests/set2/datagrid-compact.js
  gemini/tests/set2/datagrid.js
  src/clr-angular/button/button-group/button.spec.ts
  src/clr-angular/button/button-group/button.ts
  src/clr-angular/button/button-loading/loading-button.module.ts
  src/clr-angular/button/button-loading/loading-button.spec.ts
  src/clr-angular/button/button-loading/loading-button.ts
  src/clr-angular/image/_icons.clarity.scss
  src/clr-angular/progress/spinner/_spinner.clarity.scss
  src/clr-angular/utils/expand/providers/expand.spec.ts
  src/clr-angular/utils/expand/providers/expand.ts
  src/clr-angular/utils/loading/loading-listener.ts
  src/clr-angular/utils/loading/loading.spec.ts
  src/clr-angular/utils/loading/loading.ts
  src/dev/src/app/_utils/fake-loader.ts
  src/dev/src/app/buttons/button-loading.html
  src/dev/src/app/buttons/button-loading.ts
  src/ks-app/src/app/containers/data/fake-loader.ts
Labels: In Review

#2261 [CORE] Additional coding guidelines
  CODING_GUIDELINES.md
Labels: Docs, In Review

#2285 Date Picker Box Shadow
  gemini/screens/datepicker/datepicker/default/chrome.png
  gemini/screens/datepicker/monthpicker/default/chrome.png
  gemini/screens/datepicker/yearpicker/default/chrome.png
  src/clr-angular/forms/datepicker/_datepicker.clarity.scss
  src/clr-angular/popover/dropdown/_variables.dropdown.scss
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/utils/_variables.global.scss
Labels: ClarityUI, In Review

#2291 [UI, NG] Select Option Component
  src/clr-angular/forms/select/_select-angular.clarity.scss
  src/clr-angular/forms/select/all.spec.ts
  src/clr-angular/forms/select/index.ts
  src/clr-angular/forms/select/option.html
  src/clr-angular/forms/select/option.spec.ts
  src/clr-angular/forms/select/option.ts
  src/clr-angular/forms/select/options.spec.ts
  src/clr-angular/forms/select/select.module.ts
  src/clr-angular/popover/dropdown/_dropdown.clarity.scss
  src/clr-angular/popover/dropdown/_menu-mixins.clarity.scss
  src/clr-angular/popover/dropdown/_variables.dropdown.scss
  src/dev/src/app/selects/basic-ng-select.html
Labels: ClarityNG, In Review

#2284 [NG] Fix Date Picker State
  src/clr-angular/forms/datepicker/all.spec.ts
  src/clr-angular/forms/datepicker/calendar.spec.ts
  src/clr-angular/forms/datepicker/date-container.spec.ts
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
  src/clr-angular/forms/datepicker/datepicker-view-manager.spec.ts
  src/clr-angular/forms/datepicker/day.spec.ts
  src/clr-angular/forms/datepicker/day.ts
  src/clr-angular/forms/datepicker/daypicker.spec.ts
  src/clr-angular/forms/datepicker/providers/date-form-control.service.spec.ts
  src/clr-angular/forms/datepicker/providers/date-form-control.service.ts
  src/dev/src/app/datepicker/datepicker-in-reactive-forms.html
  src/dev/src/app/datepicker/datepicker-in-template-driven-forms.html
  src/dev/src/app/datepicker/datepicker-in-template-driven-forms.ts
Labels: ClarityNG, In Review

#2281 [core] deprecate code highlight (#2125)
  src/clr-angular/code/code.module.ts
  src/clr-angular/code/syntax-highlight/_code.clarity.scss
  src/clr-angular/code/syntax-highlight/syntax-highlight.module.ts
  src/clr-angular/code/syntax-highlight/syntax-highlight.spec.ts
  src/clr-angular/code/syntax-highlight/syntax-highlight.ts
  src/dev/src/app/_utils/code-example.ts
  src/dev/src/app/_utils/code.scss
  src/dev/src/app/code/code-highlight-imports.html
  src/dev/src/app/code/code-highlight-imports.ts
  src/dev/src/app/code/code-highlight-snippet.html
  src/dev/src/app/code/code-highlight-snippet.ts
  src/dev/src/app/code/code-highlight.demo.module.ts
  src/dev/src/app/code/code-highlight.demo.routing.ts
  src/dev/src/app/code/code-highlight.demo.scss
  src/dev/src/app/code/code-highlight.demo.ts
  src/dev/src/app/datagrid/utils/example.ts
  src/dev/src/app/forms-deprecated/utils/example.ts
  src/dev/src/app/tree-view/utils/example.ts
  src/ks-app/src/app/containers/code/code-snippet.component.ts
  src/ks-app/src/app/containers/code/code.component.html
  src/ks-app/src/app/containers/code/code.component.ts
Labels: In Review

#2279 [core] deprecate wizard ghost pages (#2151)
  src/clr-angular/modal/_modal.clarity.scss
  src/clr-angular/modal/modal.html
  src/clr-angular/modal/utils/ghost-page-animations.ts
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/wizard/_variables.wizard.scss
  src/clr-angular/wizard/_wizard.clarity.scss
  src/clr-angular/wizard/providers/wizard-navigation.service.ts
  src/clr-angular/wizard/wizard.html
  src/clr-angular/wizard/wizard.ts
Labels: In Review

#2277 [NG] clrDragHandle directive
  package-lock.json
  src/clr-angular/utils/drag-and-drop/all.spec.ts
  src/clr-angular/utils/drag-and-drop/drag-handle.spec.ts
  src/clr-angular/utils/drag-and-drop/drag-handle.ts
  src/clr-angular/utils/drag-and-drop/draggable.spec.ts
  src/clr-angular/utils/drag-and-drop/draggable.ts
  src/clr-angular/utils/drag-and-drop/index.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.ts
Labels: ClarityNG, In Review

#2310 [web] remove dependency on ClrCodeHighlight
  latest/src/app/documentation/demos/buttons/buttons.demo.module.ts
  latest/src/app/documentation/demos/buttons/utils/example.ts
  latest/src/app/documentation/demos/tree-view/basic-tree-node-DM/tree-node-basic-DM.html
  latest/src/app/documentation/demos/tree-view/basic-tree-view/tree-view-basic.html
  latest/src/app/documentation/demos/tree-view/label-change-on-expand/label-change-on-expand.html
  latest/src/app/documentation/demos/tree-view/lazy-loading/lazy-loading.html
  latest/src/app/documentation/demos/tree-view/tree-node-routing/tree-node-routing.html
  latest/src/app/documentation/demos/tree-view/tree-node-selection/tree-node-selection.html
  latest/src/app/documentation/demos/tree-view/tree-view-dynamic/tree-view-dynamic.html
  latest/src/app/documentation/demos/tree-view/tree-view-prepopulate/tree-view-prepopulate.html
  latest/src/app/documentation/demos/tree-view/tree-view.demo.module.ts
  latest/src/app/documentation/demos/tree-view/utils/example.ts
  latest/src/app/documentation/demos/wizard/wizard-alt-next.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-basic.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-buttons.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-custom-buttons.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-force-forward.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-jump-to.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-nested-directives.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-no-cancel.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-not-closable.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-reset.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-stop-navigation.demo.ts
  latest/src/app/documentation/demos/wizard/wizard-titles.demo.ts
  latest/src/app/utils/code-highlight.ts
  latest/src/app/utils/code-snippet.ts
  latest/src/app/utils/utils.module.ts
Labels: In Review, Website

#2316 [NG] Set isRootLevelToggle to public
  src/clr-angular/popover/dropdown/dropdown-trigger.ts
Labels: ClarityNG, In Review

#2324 [CORE] Adds Prettier.io
  .clang-format
  .editorconfig
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  scripts/clang-check.sh
  tslint.json
Labels: Build/Travis, Chore, Optimization
