Repository vmware/clarity, pull requests merged in 2018-06, with the labels that each got.

#2334 [NG] Date Picker Output Bug Fix
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
  src/clr-angular/forms/datepicker/providers/date-navigation.service.ts
  src/dev/src/app/datepicker/datepicker-in-reactive-forms.html
  src/dev/src/app/datepicker/datepicker-in-reactive-forms.ts
Labels: ClarityNG, In Review

#2348 [WEB] 0.12 New Spinner Button docs
  latest/src/app/documentation/demos/buttons/button-loading.html
  latest/src/app/documentation/demos/buttons/button-loading.ts
Labels: In Review

#2344 [ng] Clean up datagrid selection preservation (#2038)
  src/clr-angular/data/datagrid/datagrid.spec.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
  src/dev/src/app/datagrid/full/full.html
  src/dev/src/app/datagrid/full/full.ts
Labels: In Review

#2370 [WEB] Use section element in login component and docs
  src/dev/src/app/login/login.demo.html
  src/ks-app/src/app/containers/login/login.component.html
Labels: Bug, Docs

#2378 [CORE] feature: Adds automatic publishing to build repos
  .travis.yml
  scripts/publish-build.sh
Labels: Build/Travis

#2354 [NG] Input working with grid automatically, and host wrapping on inputs
  gemini/screens/input-fields/default/chrome.png
  gemini/screens/landing-page/default/chrome.png
  gemini/screens/landing-page/setting-clicked/chrome.png
  gemini/screens/landing-page/setting-hovered/chrome.png
  gemini/screens/landing-page/sidenav-hovered/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  src/clr-angular/forms/common/all.spec.ts
  src/clr-angular/forms/common/common.module.ts
  src/clr-angular/forms/common/form.spec.ts
  src/clr-angular/forms/common/form.ts
  src/clr-angular/forms/common/label.spec.ts
  src/clr-angular/forms/common/label.ts
  src/clr-angular/forms/common/layout.spec.ts
  src/clr-angular/forms/common/layout.ts
  src/clr-angular/forms/common/providers/control-class.service.ts
  src/clr-angular/forms/common/providers/layout.service.spec.ts
  src/clr-angular/forms/common/providers/layout.service.ts
  src/clr-angular/forms/common/wrapped-control.spec.ts
  src/clr-angular/forms/common/wrapped-control.ts
  src/clr-angular/forms/input/input-container.spec.ts
  src/clr-angular/forms/input/input-container.ts
  src/clr-angular/forms/input/input.spec.ts
  src/clr-angular/forms/input/input.ts
  src/clr-angular/forms/styles/_containers.clarity.scss
  src/clr-angular/forms/styles/_input.clarity.scss
  src/clr-angular/utils/host-wrapping/host-wrapper.ts
  src/dev/src/app/app.routing.ts
  src/dev/src/app/forms/layout/layout.html
  src/dev/src/app/forms/reactive/reactive.html
  src/dev/src/app/forms/template-driven/template-driven.html
  src/dev/src/app/input-fields/input-fields.demo.html
  src/dev/src/app/input/input.demo.html
  src/dev/src/app/input/input.demo.module.ts
  src/dev/src/app/input/input.demo.routing.ts
  src/dev/src/app/input/input.demo.ts
Labels: ClarityNG, Enhancement, In Review

#2381 [ng] Datagrid bug fix for when selection is cleared by applying filter
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
Labels: Bug, ClarityNG

#2398 [NG] fix layout to not use Object.values since its not ie11 supported
  src/clr-angular/forms/common/layout.ts
  src/clr-angular/forms/common/providers/layout.service.spec.ts
  src/clr-angular/forms/common/providers/layout.service.ts
Labels: In Review

#2409 [UI] Alerts overflow bug fix
  src/clr-angular/emphasis/alert/_alert.clarity.scss
Labels: ClarityUI, In Review
