Repository vmware/clarity, pull requests merged in 2018-04, with the labels that each got.

#2106 [WIP | NG] ClrDragEventListener implementation
  src/clr-angular/utils/drag-and-drop/all.spec.ts
  src/clr-angular/utils/drag-and-drop/interfaces/drag-event.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.ts
Labels: In Review

#2179 [UI] fix: dark theme
  src/clr-angular/data/_tables.clarity.scss
Labels: Dark theme

#2187 [NG] Ignore Element Click while toggling Popovers
  gemini/screens/landing-page/default/chrome.png
  gemini/screens/landing-page/setting-clicked/chrome.png
  gemini/screens/landing-page/setting-hovered/chrome.png
  gemini/screens/landing-page/sidenav-hovered/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  package-lock.json
  package.json
  src/app/app.routing.ts
  src/app/popovers/dummy-anchor.ts
  src/app/popovers/dummy-menu.ts
  src/app/popovers/popovers.demo.html
  src/app/popovers/popovers.demo.module.ts
  src/app/popovers/popovers.demo.routing.ts
  src/app/popovers/popovers.demo.scss
  src/app/popovers/popovers.demo.ts
  src/clr-angular/popover/common/abstract-popover.spec.ts
  src/clr-angular/popover/common/abstract-popover.ts
Labels: ClarityNG, Internal

#2173 [NG] bare draggable and droppable with demo setup
  gemini/screens/landing-page/default/chrome.png
  gemini/screens/landing-page/setting-clicked/chrome.png
  gemini/screens/landing-page/setting-hovered/chrome.png
  gemini/screens/landing-page/sidenav-hovered/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  src/app/app.routing.ts
  src/app/drag-and-drop/basic-draggable.demo.html
  src/app/drag-and-drop/basic-draggable.demo.ts
  src/app/drag-and-drop/drag-and-drop.demo.html
  src/app/drag-and-drop/drag-and-drop.demo.module.ts
  src/app/drag-and-drop/drag-and-drop.demo.routing.ts
  src/app/drag-and-drop/drag-and-drop.demo.scss
  src/app/drag-and-drop/drag-and-drop.demo.ts
  src/app/drag-and-drop/draggable-handle.demo.html
  src/app/drag-and-drop/draggable-handle.demo.ts
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/utils/drag-and-drop/drag-and-drop.module.ts
  src/clr-angular/utils/drag-and-drop/draggable.ts
  src/clr-angular/utils/drag-and-drop/droppable.ts
  src/clr-angular/utils/drag-and-drop/index.ts
  src/clr-angular/utils/index.ts
Labels: In Review

#2195 fix: [UI] breakpoints to be overwritable
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/tests/set4/wizard.js
  src/clr-angular/utils/_components.clarity.scss
  src/clr-angular/utils/_dependencies.clarity.scss
Labels: ClarityUI

#2201 [UI] Breakpoints to be overwritable (#2195)
  src/app/_utils/code.scss
  src/app/layout/layout.demo.scss
  src/app/vertical-nav/vertical-nav.demo.scss
  src/clr-angular/emphasis/alert/_alert.clarity.scss
  src/clr-angular/forms-deprecated/_forms.clarity.scss
  src/clr-angular/layout/_card.clarity.scss
  src/clr-angular/layout/_login.clarity.scss
  src/clr-angular/layout/nav/_header.clarity.scss
  src/clr-angular/layout/nav/_responsive-nav.clarity.scss
  src/clr-angular/modal/_modal.clarity.scss
  src/clr-angular/popover/dropdown/_dropdown.clarity.scss
  src/clr-angular/typography/_typography.clarity.scss
  src/clr-angular/utils/_bs4-grid-breakpoint-overrides.clarity.scss
  src/clr-angular/utils/_components.clarity.scss
  src/clr-angular/utils/_dependencies.clarity.scss
  src/clr-angular/utils/_maps.clarity.scss
  src/clr-angular/utils/_overwrites.clarity.scss
Labels: ClarityUI, Dark theme

#2210 [UI] Button Group Radio Fix
  gemini/screens/button-group/angular-checkboxes/default/chrome.png
  gemini/screens/button-group/cards/default/chrome.png
  gemini/screens/button-group/checkboxes-checked-1/default/chrome.png
  gemini/screens/button-group/checkboxes-checked-2/default/chrome.png
  gemini/screens/button-group/checkboxes/default/chrome.png
  gemini/screens/button-group/radios-checked/default/chrome.png
  gemini/screens/button-group/radios/default/chrome.png
  gemini/screens/vertical-nav/routing/default/chrome.png
  src/clr-angular/button/_buttons.clarity.scss
Labels: ClarityUI

#2216 [NG] Add tab link type attribute.
  src/clr-angular/layout/tabs/tab-link.directive.ts
  src/clr-angular/layout/tabs/tabs.ts
Labels: ClarityNG

#2189 [NG] emitting on string filter value change
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
  src/ks-app/src/app/containers/data/datagrid.component.html
Labels: ClarityNG, In Review
