Repository vmware/clarity, pull requests merged in 2018-10, with the labels that each got.

#2693 [NG] improve radio inline with error formatting
  .gitignore
  gemini/screens/forms/form-checkbox/default/chrome.png
  gemini/screens/forms/form-compact/default/chrome.png
  gemini/screens/forms/form-horizontal/default/chrome.png
  gemini/screens/forms/form-radio/default/chrome.png
  gemini/screens/forms/form-vertical/default/chrome.png
  gemini/screens/input/default/chrome.png
  gemini/screens/radios/default/chrome.png
  gemini/screens/selects/default/chrome.png
  gemini/screens/textarea/default/chrome.png
  src/clr-angular/forms/common/providers/control-class.service.spec.ts
  src/clr-angular/forms/common/providers/control-class.service.ts
  src/clr-angular/forms/radio/radio-container.spec.ts
  src/clr-angular/forms/radio/radio-container.ts
  src/clr-angular/forms/styles/_containers.clarity.scss
  src/clr-angular/forms/styles/_radio.clarity.scss
  src/clr-angular/forms/styles/containers.spec.ts
  src/dev/src/app/forms/controls/checkbox.html
  src/dev/src/app/forms/controls/radio.html
  src/dev/src/app/forms/layout/layout.html
  src/dev/src/app/radios/radios.demo.html
Labels: Accepted, In Review

#2706 [BUG] Making action red accessible against #FAFAFA background
  gemini/screens/color/color-palette/default/chrome.png
  src/clr-angular/color/utils/_colors.clarity.scss
  src/clr-angular/color/utils/_contrast-cache.clarity.scss
  src/clr-angular/utils/_overwrites.clarity.scss
  src/clr-icons/clr-icons.scss
  src/clr-icons/shapes/technology-shapes.ts
  src/dev/src/app/color/color-palette.ts
  src/ks-app/src/app/containers/colors/colors.component.ts
Labels: PR Target: Master & Patch

#2723 [Docs] Warn against full-row click
  latest/src/app/documentation/demos/datagrid/single-selection/single-selection.html
Labels: Website

#2730 [NG] Replace old forms module
  golden/clr-angular.d.ts
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/data/datagrid/datagrid.module.ts
  src/clr-angular/data/tree-view/tree-view.module.ts
  src/clr-angular/forms-deprecated/checkbox/checkbox.spec.ts
  src/clr-angular/forms-deprecated/forms.module.ts
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/forms.module.ts
  src/dev/src/app/button-group/button-group.demo.module.ts
  src/dev/src/app/checkboxes/checkboxes.demo.module.ts
  src/dev/src/app/datagrid/datagrid.demo.module.ts
  src/dev/src/app/datepicker/datepicker.demo.module.ts
  src/dev/src/app/forms/forms.demo.module.ts
  src/dev/src/app/input/input.demo.module.ts
  src/dev/src/app/password/password.demo.module.ts
  src/dev/src/app/radios/radios.demo.module.ts
  src/dev/src/app/selects/selects.demo.module.ts
  src/dev/src/app/textarea/textarea.demo.module.ts
  src/ks-app/src/app/app.module.ts
Labels: Breaking Change

#2726 [NG] Switch our global providers to the tree-shakeable syntax
  src/clr-angular/layout/nav/navigation.module.ts
  src/clr-angular/layout/nav/providers/responsive-navigation.provider.ts
  src/clr-angular/layout/nav/providers/responsive-navigation.service.ts
  src/clr-angular/popover/signpost/signpost.module.ts
  src/clr-angular/utils/drag-and-drop/drag-and-drop.module.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.service.ts
  src/clr-angular/utils/focus-trap/focus-trap-tracker.service.ts
  src/clr-angular/utils/focus-trap/focus-trap.module.ts
Labels: Bug, Dev

#2727 [0.12 backport] Switch our global providers to the tree-shakeable syntax
  src/clr-angular/layout/nav/navigation.module.ts
  src/clr-angular/layout/nav/providers/responsive-navigation.provider.ts
  src/clr-angular/layout/nav/providers/responsive-navigation.service.ts
  src/clr-angular/popover/signpost/signpost.module.ts
  src/clr-angular/utils/focus-trap/focus-trap-tracker.service.ts
  src/clr-angular/utils/focus-trap/focus-trap.module.ts
Labels: Bug, Dev

#2748 [WEB] Add 'xl' value in the modal page in summary section
  latest/src/app/documentation/demos/modal/modal.demo.html
Labels: Website

#2761 Fix modal boolean testing
  src/clr-angular/modal/modal.ts
Labels: Dev

#2738 Add two-way binding to ClrDatagridHideableColumn
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.ts
Labels: Dev, Enhancement

#2758 [NG] remove deprecated wizard features
  golden/clr-angular.d.ts
  src/clr-angular/wizard/providers/wizard-navigation.service.spec.ts
  src/clr-angular/wizard/providers/wizard-navigation.service.ts
  src/clr-angular/wizard/wizard.spec.ts
  src/clr-angular/wizard/wizard.ts
Labels: Deprecation

#2756 [NG] remove deprecated datagrid features
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
  src/clr-angular/data/datagrid/datagrid.spec.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
  src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
Labels: Deprecation

#2750 [ICONS] remove deprecated shapes for 1.0
  gemini/dark-screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  src/clr-angular/deprecations.spec.ts
  src/clr-icons/shapes/essential-shapes.ts
Labels: Deprecation

#2776 [a11y] Adding aria-labelledby to modals
  golden/clr-angular.d.ts
  src/clr-angular/modal/_modal.clarity.scss
  src/clr-angular/modal/modal.html
  src/clr-angular/modal/modal.ts
Labels: Accessibility, Dev, PR Target: Master & Patch

#2757 [UI] Adds a backward compatibility solution for deprecated-grid
  angular.json
  package.json
  src/clr-angular/layout/_grid-deprecated.clarity.scss
  src/clr-angular/layout/grid-deprecated.clarity.scss
  src/clr-angular/utils/_components.clarity.scss
Labels: Breaking Change, Deprecation

#2751 [NG] remove support for deprecated `alert-X` variations of alert types
  src/clr-angular/emphasis/alert/alert-item.ts
  src/clr-angular/emphasis/alert/alert.spec.ts
  src/clr-angular/emphasis/alert/alerts-pager.spec.ts
  src/clr-angular/emphasis/alert/alerts.spec.ts
  src/clr-angular/emphasis/alert/alerts.ts
  src/clr-angular/emphasis/alert/all.spec.ts
  src/clr-angular/emphasis/alert/providers/icon-and-types.service.spec.ts
  src/clr-angular/emphasis/alert/providers/icon-and-types.service.ts
  src/clr-angular/emphasis/alert/providers/multi-alert.service.spec.ts
  src/clr-angular/emphasis/alert/utils/alert-types.ts
  src/dev/src/app/alert/angular/alert-angular-app-level-alerts.demo.html
  src/dev/src/app/alert/angular/alert-angular-app-level.demo.html
  src/dev/src/app/alert/angular/alert-angular-close-event.demo.html
  src/dev/src/app/alert/angular/alert-angular-not-closable.demo.html
  src/dev/src/app/alert/angular/alert-angular-small.demo.html
  src/dev/src/app/alert/angular/alert-angular-success.demo.html
  src/dev/src/app/wizard/wizard-async-validation.demo.html
Labels: Deprecation
