Repository vmware/clarity, pull requests merged in 2018-08, with the labels that each got.

#2347 [NG] Proper Datagrid typing
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/all.spec.ts
  src/clr-angular/data/datagrid/built-in/comparators/datagrid-property-comparator.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-property-string-filter.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter-impl.spec.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter-impl.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.spec.ts
  src/clr-angular/data/datagrid/built-in/filters/datagrid-string-filter.ts
  src/clr-angular/data/datagrid/built-in/nested-property.ts
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
  src/clr-angular/data/datagrid/datagrid-filter.spec.ts
  src/clr-angular/data/datagrid/datagrid-filter.ts
  src/clr-angular/data/datagrid/datagrid-footer.spec.ts
  src/clr-angular/data/datagrid/datagrid-footer.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.model.spec.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.ts
  src/clr-angular/data/datagrid/datagrid-items-trackby.spec.ts
  src/clr-angular/data/datagrid/datagrid-items-trackby.ts
  src/clr-angular/data/datagrid/datagrid-items.spec.ts
  src/clr-angular/data/datagrid/datagrid-items.ts
  src/clr-angular/data/datagrid/datagrid-placeholder.spec.ts
  src/clr-angular/data/datagrid/datagrid-placeholder.ts
  src/clr-angular/data/datagrid/datagrid-row-detail.spec.ts
  src/clr-angular/data/datagrid/datagrid-row-detail.ts
  src/clr-angular/data/datagrid/datagrid-row.spec.ts
  src/clr-angular/data/datagrid/datagrid-row.ts
  src/clr-angular/data/datagrid/datagrid.module.ts
  src/clr-angular/data/datagrid/datagrid.spec.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/interfaces/state.interface.ts
  src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
  src/clr-angular/data/datagrid/providers/drag-dispatcher.ts
  src/clr-angular/data/datagrid/providers/filters.spec.ts
  src/clr-angular/data/datagrid/providers/filters.ts
  src/clr-angular/data/datagrid/providers/items.spec.ts
  src/clr-angular/data/datagrid/providers/items.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
  src/clr-angular/data/datagrid/providers/sort.spec.ts
  src/clr-angular/data/datagrid/providers/sort.ts
  src/clr-angular/data/datagrid/providers/state.provider.ts
  src/clr-angular/data/datagrid/render/column-resizer.spec.ts
  src/clr-angular/data/datagrid/render/main-renderer.spec.ts
  src/clr-angular/data/datagrid/render/main-renderer.ts
  src/clr-angular/data/datagrid/utils/datagrid-filter-registrar.ts
  src/dev/src/app/datagrid/server-driven/server-driven.ts
  src/ks-app/src/app/containers/data/datagrid.component.ts
Labels: Accepted, ClarityNG, Enhancement, Internal

#2422 [NG] clrDroppable and more tests
  src/clr-angular/utils/drag-and-drop/_drag-and-drop.clarity.scss
  src/clr-angular/utils/drag-and-drop/all.spec.ts
  src/clr-angular/utils/drag-and-drop/drag-and-drop-integrated.spec.ts
  src/clr-angular/utils/drag-and-drop/drag-event.ts
  src/clr-angular/utils/drag-and-drop/drag-handle.ts
  src/clr-angular/utils/drag-and-drop/draggable-ghost.ts
  src/clr-angular/utils/drag-and-drop/draggable/custom-ghost-integration.spec.ts
  src/clr-angular/utils/drag-and-drop/draggable/draggable.spec.ts
  src/clr-angular/utils/drag-and-drop/draggable/draggable.ts
  src/clr-angular/utils/drag-and-drop/draggable/ghost-and-handle-integration.spec.ts
  src/clr-angular/utils/drag-and-drop/droppable.ts
  src/clr-angular/utils/drag-and-drop/droppable/droppable.spec.ts
  src/clr-angular/utils/drag-and-drop/droppable/droppable.ts
  src/clr-angular/utils/drag-and-drop/if-dragged.ts
  src/clr-angular/utils/drag-and-drop/index.ts
  src/clr-angular/utils/drag-and-drop/interfaces/drag-event.ts
  src/clr-angular/utils/drag-and-drop/interfaces/drop-tolerance.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-and-drop-event-bus.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.mock.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-handle-registrar.ts
  src/clr-angular/utils/drag-and-drop/providers/draggable-snapshot.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/draggable-snapshot.ts
Labels: Accepted, ClarityNG, In Review

#2523 [BUG] Odd wizard vertical height issue when resizing browser
  src/clr-angular/wizard/_wizard.clarity.scss
Labels: Bug, Dev

#2485 clrSelect
  gemini/screens/forms/form-compact/default/chrome.png
  gemini/screens/forms/form-horizontal/default/chrome.png
  gemini/screens/forms/form-select/default/chrome.png
  gemini/screens/forms/form-vertical/default/chrome.png
  gemini/screens/selects/default/chrome.png
  gemini/tests/set3/selects.js
  golden/clr-angular.d.ts
  package-lock.json
  package.json
  src/clr-angular/forms/forms.module.ts
  src/clr-angular/forms/index.ts
  src/clr-angular/forms/select/all.spec.ts
  src/clr-angular/forms/select/index.ts
  src/clr-angular/forms/select/select-container.spec.ts
  src/clr-angular/forms/select/select-container.ts
  src/clr-angular/forms/select/select.module.ts
  src/clr-angular/forms/select/select.spec.ts
  src/clr-angular/forms/select/select.ts
  src/clr-angular/forms/styles/_select.clarity.scss
  src/clr-angular/forms/styles/containers.spec.ts
  src/dev/src/app/selects/selects.demo.html
  src/dev/src/app/selects/selects.demo.module.ts
  src/dev/src/app/selects/selects.demo.ts
Labels: Accepted, In Review

#2530 Update DEVELOPMENT_CONTRIBUTION.md
  DEVELOPMENT_CONTRIBUTION.md
Labels: Chore, In Review

#2526 [NG] Remove the forRoot and forChild methods from ClarityModule
  golden/clr-angular.d.ts
  npm/clr-angular/package.json
  npm/clr-icons/package.json
  npm/clr-ui/package.json
  package-lock.json
  package.json
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/data/datagrid/helpers.spec.ts
  src/clr-angular/package.json
  src/schematics/README.md
  src/schematics/src/collection.json
  src/schematics/src/migration-collection.json
  src/schematics/src/update/update-0.13.0-beta.1.ts
Labels: In Review

#2519 [ng] allow pre-selection of currentSingle when `all` hasn't been set
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
  src/dev/src/app/datagrid/selection-single/selection-single.html
Labels: In Review

#2545 [web] updating dox on datagrid batch action to include export (#2286)
  latest/src/app/documentation/demos/datagrid/batch-action/batch-action.html
  latest/src/app/documentation/demos/datagrid/batch-action/batch-action.ts
  v0.11/package-lock.json
Labels: In Review

#2520 Create new issue templates for bug and features
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/contribution-proposal.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: In Review

#2546 [ng] Remove OK/Apply button from column hide/show panel in datagrid
  src/clr-angular/data/datagrid/datagrid-column-toggle-button.spec.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.ts
  src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.spec.ts
  src/clr-angular/data/datagrid/providers/column-toggle-buttons.service.ts
  src/dev/src/app/datagrid/hide-show-columns/hide-show.html
Labels: In Review

#2559 [UI] Remove push/pull from old grid (#2143)
  gemini/screens/grid-deprecated/grid-column-pull/default/chrome.png
  gemini/screens/grid-deprecated/grid-column-push/default/chrome.png
  gemini/tests/set2/grid-deprecated.js
  src/clr-angular/layout/grid/mixins/_grid-framework.clarity.scss
  src/dev/src/app/grid-deprecated/grid-column-pull.html
  src/dev/src/app/grid-deprecated/grid-column-pull.ts
  src/dev/src/app/grid-deprecated/grid-column-push.html
  src/dev/src/app/grid-deprecated/grid-column-push.ts
  src/dev/src/app/grid-deprecated/grid.demo.module.ts
  src/dev/src/app/grid-deprecated/grid.demo.routing.ts
  src/dev/src/app/grid-deprecated/grid.demo.ts
Labels: In Review

#2557 Remove ClrCodeHighlight and update schematics
  gemini/tests/set1/code-highlight.js
  golden/clr-angular.d.ts
  package.json
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/code/code.module.ts
  src/clr-angular/code/index.ts
  src/clr-angular/code/syntax-highlight/index.ts
  src/clr-angular/code/syntax-highlight/syntax-highlight.module.ts
  src/clr-angular/code/syntax-highlight/syntax-highlight.spec.ts
  src/clr-angular/code/syntax-highlight/syntax-highlight.ts
  src/clr-angular/index.ts
  src/clr-angular/package.json
  src/clr-angular/typography/_code.clarity.scss
  src/clr-angular/utils/_components.clarity.scss
  src/dev/src/app/login/login.demo.html
  src/dev/src/app/nav/responsive-nav1.ts
  src/dev/src/app/nav/responsive-nav2.ts
  src/ks-app/src/app/app-routing.module.ts
  src/ks-app/src/app/app.module.ts
  src/ks-app/src/app/containers/code/code-snippet.component.ts
  src/ks-app/src/app/containers/code/code.component.html
  src/ks-app/src/app/containers/code/code.component.ts
  src/schematics/src/add/schema.d.ts
  src/schematics/src/migration-collection.json
  src/schematics/src/update/update-0.13.0-beta.1.ts
  src/schematics/src/update/update-0.13.0.ts
Labels: In Review

#2552 [ICONS] Clean up deprecated icons (#2147)
  gemini/screens/iconography/selection-core-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-core-shapes/line/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-media-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-media-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-media-shapes/line/chrome.png
  gemini/screens/iconography/selection-media-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-media-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-media-shapes/solid/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid/chrome.png
  src/clr-icons/shapes/chart-shapes.ts
  src/clr-icons/shapes/core-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/media-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
  src/dev/src/app/tree-view/tree-view-dynamic/tree-view-dynamic.ts
Labels: In Review

#2494 [NG] clrRadio component for new forms
  gemini/screens/radios/default/chrome.png
  gemini/tests/set3/radios.js
  golden/clr-angular.d.ts
  src/clr-angular/forms/common/label.spec.ts
  src/clr-angular/forms/common/label.ts
  src/clr-angular/forms/radio/all.spec.ts
  src/clr-angular/forms/radio/index.ts
  src/clr-angular/forms/radio/radio-container.spec.ts
  src/clr-angular/forms/radio/radio-container.ts
  src/clr-angular/forms/radio/radio-wrapper.spec.ts
  src/clr-angular/forms/radio/radio-wrapper.ts
  src/clr-angular/forms/radio/radio.module.ts
  src/clr-angular/forms/radio/radio.spec.ts
  src/clr-angular/forms/radio/radio.ts
  src/clr-angular/forms/styles/_radio.clarity.scss
  src/clr-angular/forms/tests/container.spec.ts
  src/clr-angular/forms/tests/wrapper.spec.ts
  src/dev/src/app/radios/radios.demo.html
  src/dev/src/app/radios/radios.demo.module.ts
  src/dev/src/app/radios/radios.demo.ts
Labels: Accepted, Enhancement, In Review

#2561 [ICONS] Vol12 Icons
  gemini/screens/iconography/selection-commerce-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/line/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid/chrome.png
  gemini/screens/iconography/selection-travel-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-travel-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-travel-shapes/line/chrome.png
  src/clr-icons/shapes/commerce-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
Labels: Icons, In Review

#2578 [NG] Schematics update for using bootstrap's push / pull in Clarity grid
  src/schematics/src/update/update-0.13.0.ts
Labels: In Review

#2577 [NG] Schematics update for deprecated icons
  src/schematics/src/update/update-0.13.0.ts
Labels: In Review

#2610 [CORE] Update karma.conf
  karma.conf.js
Labels: Build

#2579 [NG] Schematics update for importing deprecated non-Clr classes
  src/schematics/src/migration-collection.json
  src/schematics/src/update/update-0.13.0.ts
Labels: In Review
