Repository vmware/clarity, pull requests merged in 2018-07, with the labels that each got.

#2408 feature: [CORE] Repo guard & slack integration
  .travis.yml
Labels: Build/Travis

#2414 [NG] Fix tooltip visibility issue on trigger focus
  src/clr-angular/forms/common/layout.ts
  src/clr-angular/popover/tooltip/_tooltips.clarity.scss
  src/clr-angular/popover/tooltip/tooltip-trigger.ts
Labels: ClarityNG, In Review

#2416 [NG] fix import paths for dev app
  src/dev/src/app/alert/alert.demo.routing.ts
  src/dev/src/app/badges/badges.demo.routing.ts
  src/dev/src/app/button-group/button-group.demo.routing.ts
  src/dev/src/app/buttons/buttons.demo.routing.ts
  src/dev/src/app/card/card.demo.routing.ts
  src/dev/src/app/checkboxes/checkboxes.demo.routing.ts
  src/dev/src/app/color/color.demo.routing.ts
  src/dev/src/app/datagrid/datagrid.demo.routing.ts
  src/dev/src/app/dropdown/dropdown.demo.routing.ts
  src/dev/src/app/forms-deprecated/forms.demo.routing.ts
  src/dev/src/app/grid-deprecated/grid.demo.routing.ts
  src/dev/src/app/iconography/iconography.demo.routing.ts
  src/dev/src/app/images/images.demo.routing.ts
  src/dev/src/app/input-fields/input-fields.demo.routing.ts
  src/dev/src/app/input/input.demo.routing.ts
  src/dev/src/app/labels/labels.demo.routing.ts
  src/dev/src/app/layout/layout.demo.routing.ts
  src/dev/src/app/lists/lists.demo.routing.ts
  src/dev/src/app/login/login.demo.routing.ts
  src/dev/src/app/modal/modal.demo.routing.ts
  src/dev/src/app/nav/nav.demo.routing.ts
  src/dev/src/app/popovers/popovers.demo.routing.ts
  src/dev/src/app/progress-bars/progress-bars.demo.routing.ts
  src/dev/src/app/radios/radios.demo.routing.ts
  src/dev/src/app/selects/selects.demo.routing.ts
  src/dev/src/app/signpost/signpost.routing.ts
  src/dev/src/app/spinners/spinners.demo.routing.ts
  src/dev/src/app/stack-view/stack-view.demo.routing.ts
  src/dev/src/app/tables/tables.demo.routing.ts
  src/dev/src/app/tabs/tabs.demo.routing.ts
  src/dev/src/app/toggles/toggles.demo.routing.ts
  src/dev/src/app/tooltips/tooltips.demo.routing.ts
  src/dev/src/app/tree-view/tree-view.demo.routing.ts
  src/dev/src/app/typography/typography.demo.routing.ts
  src/dev/src/app/vertical-nav/vertical-nav.demo.routing.ts
  src/dev/src/app/virtual-scroll/virtual-scroll.demo.routing.ts
Labels: In Review

#2413 Schematic fix for webcomponents script ordering and monorepo support
  src/schematics/src/add/index.ts
  src/schematics/src/add/schema.d.ts
  src/schematics/src/add/schema.json
Labels: In Review, Schematics

#2395 [NG] Select an Option
  gemini/screens/alert/styles/default/chrome.png
  gemini/screens/button-group/basic-structure flat with overflow menu/default/chrome.png
  gemini/screens/button-group/basic-structure with overflow menu/default/chrome.png
  gemini/screens/button-group/icons-with-text/default/chrome.png
  gemini/screens/card/dropdown/default/chrome.png
  gemini/screens/dropdown/angular-nested/clicked/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-left/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-right/chrome.png
  gemini/screens/dropdown/angular-positioning/deprecated-clicked/chrome.png
  gemini/screens/dropdown/angular-positioning/if-open-clicked/chrome.png
  gemini/screens/dropdown/angular-positioning/no-if-open-clicked/chrome.png
  gemini/screens/dropdown/buttonlink-toggle/default/chrome.png
  gemini/screens/dropdown/default/default/chrome.png
  gemini/screens/dropdown/dropdown-header/click the dropdown toggle/chrome.png
  gemini/screens/dropdown/positioning/default/chrome.png
  gemini/screens/navigation/header-types/header-dropdown/chrome.png
  gemini/screens/tabs/static/default/chrome.png
  src/clr-angular/forms/select/_select-angular.clarity.scss
  src/clr-angular/forms/select/all.spec.ts
  src/clr-angular/forms/select/option.spec.ts
  src/clr-angular/forms/select/option.ts
  src/clr-angular/forms/select/providers/option-selection.service.spec.ts
  src/clr-angular/forms/select/providers/option-selection.service.ts
  src/clr-angular/forms/select/select-with-option.integration.spec.ts
  src/clr-angular/forms/select/select-with-options-menu.integration.spec.ts
  src/clr-angular/forms/select/select.spec.ts
  src/clr-angular/forms/select/select.ts
  src/clr-angular/forms/select/utils/select-dom-adapter.ts
  src/clr-angular/forms/select/utils/select-noop-dom-adapter.ts
  src/clr-angular/popover/dropdown/_menu-mixins.clarity.scss
  src/dev/src/app/selects/basic-ng-select.html
  src/dev/src/app/selects/optional-menu.html
Labels: ClarityNG, Enhancement, In Review

#2440 [NG] Add Stack View aria-expanded attribute
  src/clr-angular/data/stack-view/stack-block.spec.ts
  src/clr-angular/data/stack-view/stack-block.ts
Labels: ClarityNG, In Review

#2421 [ng] Bug fix on spinner button to work with [disabled] input (#2375)
  src/clr-angular/button/button-loading/loading-button.spec.ts
  src/clr-angular/button/button-loading/loading-button.ts
  src/dev/src/app/buttons/button-loading.html
  src/dev/src/app/buttons/button-loading.ts
Labels: ClarityNG

#2445 Reactive form fix, and tests
  src/clr-angular/forms/input/input-container.spec.ts
  src/clr-angular/forms/input/input.spec.ts
  src/clr-angular/forms/input/input.ts
  src/clr-angular/forms/tests/container.spec.ts
  src/clr-angular/forms/tests/control.spec.ts
  src/clr-angular/forms/textarea/textarea-container.spec.ts
  src/clr-angular/forms/textarea/textarea.spec.ts
  src/clr-angular/forms/textarea/textarea.ts
Labels: ClarityNG, In Review

#2451 [NG] Stack View AOT Fix
  src/clr-angular/data/stack-view/stack-block.ts
Labels: ClarityNG, In Review

#2447 [NG] Signpost focus state accessibility fixes
  src/clr-angular/popover/signpost/_signposts.clarity.scss
  src/clr-angular/popover/signpost/_variables.signpost.scss
  src/dev/src/app/signpost/signpost.demo.html
Labels: ClarityNG

#2457 [NG] Export Conditional and Expand Directives
  src/clr-angular/utils/conditional/if-active.directive.spec.ts
  src/clr-angular/utils/conditional/if-active.directive.ts
  src/clr-angular/utils/conditional/if-open.directive.spec.ts
  src/clr-angular/utils/conditional/if-open.directive.ts
  src/clr-angular/utils/conditional/index.ts
  src/clr-angular/utils/expand/if-expanded.spec.ts
  src/clr-angular/utils/expand/if-expanded.ts
  src/clr-angular/utils/expand/index.ts
  src/clr-angular/utils/index.ts
Labels: ClarityNG, In Review

#2467 fix(CORE): Update travis secure token and fix slack integration.
  .travis.yml
Labels: Build/Travis, In Review

#2471 [NG] ARIA attributes for TreeView
  src/clr-angular/data/tree-view/tree-node.html
  src/clr-angular/data/tree-view/tree-node.spec.ts
  src/clr-angular/data/tree-view/tree-node.ts
Labels: ClarityNG, DO NOT MERGE, In Review

#2453 [WEB] Adding hiring banner to latest dox
  latest/src/app/app.component.html
  latest/src/app/app.component.ts
  latest/src/app/community/community.component.html
  latest/src/app/community/community.component.ts
  latest/src/assets/images/caterpillar.svg
  latest/src/index.html
Labels: Website

#2476 fix(UI): adjusts font size and line-height for required form inputs
  gemini/screens/forms-deprecated/form-compact/default/chrome.png
  gemini/screens/forms-deprecated/form-validation/default/chrome.png
  src/clr-angular/forms-deprecated/_forms.clarity.scss
Labels: ClarityUI, In Review

#2480 [DOX] Adding v0.12 stack blitz links to readme
  .github/ISSUE_TEMPLATE.md
  README.md
  golden/clr-angular.d.ts
Labels: Docs

#2417 [NG] clrPassword component
  gemini/screens/iconography/selection-core-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-core-shapes/line/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid/chrome.png
  gemini/screens/landing-page/default/chrome.png
  gemini/screens/landing-page/setting-clicked/chrome.png
  gemini/screens/landing-page/setting-hovered/chrome.png
  gemini/screens/landing-page/sidenav-hovered/chrome.png
  gemini/screens/password/default/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  gemini/tests/set3/password.js
  golden/clr-angular.d.ts
  package.json
  src/clr-angular/deprecations.spec.ts
  src/clr-angular/forms/common/providers/focus.service.ts
  src/clr-angular/forms/forms.module.ts
  src/clr-angular/forms/index.ts
  src/clr-angular/forms/input/input-container.ts
  src/clr-angular/forms/password/all.spec.ts
  src/clr-angular/forms/password/index.ts
  src/clr-angular/forms/password/password-container.spec.ts
  src/clr-angular/forms/password/password-container.ts
  src/clr-angular/forms/password/password.module.ts
  src/clr-angular/forms/password/password.spec.ts
  src/clr-angular/forms/password/password.ts
  src/clr-angular/forms/styles/_input-group.clarity.scss
  src/clr-angular/forms/tests/container.spec.ts
  src/clr-angular/forms/tests/control.spec.ts
  src/clr-angular/forms/textarea/textarea-container.ts
  src/clr-icons/shapes/core-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/dev/src/app/app.routing.ts
  src/dev/src/app/password/password.demo.html
  src/dev/src/app/password/password.demo.module.ts
  src/dev/src/app/password/password.demo.routing.ts
  src/dev/src/app/password/password.demo.ts
Labels: ClarityNG, In Review

#2473 [NG] Change locale strings to nominative form
  src/clr-angular/forms/datepicker/providers/locale-helper.service.spec.ts
  src/clr-angular/forms/datepicker/providers/locale-helper.service.ts
Labels: ClarityNG, In Review

#2489 [BUG] Setting progress bar color values to expected vars and adding d…
  src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
  src/clr-angular/progress/progress-bars/_variables.progress-bars.scss
Labels: ClarityUI

#2490 fix(core): clang formatting for code ported from v12.
  gemini/screens/datagrid-compact/datagrid-compact-with-signpost/default/chrome.png
  gemini/screens/forms-deprecated/form-validation/default/chrome.png
  gemini/screens/signposts/bottom-left/chrome.png
  gemini/screens/signposts/bottom-middle/chrome.png
  gemini/screens/signposts/bottom-right/chrome.png
  gemini/screens/signposts/default/chrome.png
  gemini/screens/signposts/left-bottom/chrome.png
  gemini/screens/signposts/left-middle/chrome.png
  gemini/screens/signposts/left-top/chrome.png
  gemini/screens/signposts/right-bottom/chrome.png
  gemini/screens/signposts/right-middle/chrome.png
  gemini/screens/signposts/right-top/chrome.png
  gemini/screens/signposts/top-left/chrome.png
  gemini/screens/signposts/top-middle/chrome.png
  gemini/screens/signposts/top-right/chrome.png
  gemini/screens/stack-view/angular-basic/default/chrome.png
  gemini/screens/stack-view/angular-lazyload/default/chrome.png
  src/clr-angular/data/stack-view/stack-block.spec.ts
  src/clr-angular/data/stack-view/stack-block.ts
  src/clr-angular/data/stack-view/stack-view.module.ts
Labels: Accepted, Build/Travis, In Review
