Repository vmware/clarity, pull requests merged in 2018-11, with the labels that each got.

#2773 [NG] Check listener is defined before invoking it
  src/clr-angular/utils/loading/loading.spec.ts
  src/clr-angular/utils/loading/loading.ts
Labels: PR Target: Master & Patch

#2803 Datepicker bugfixes
  gemini/dark-screens/datepicker/layout/default/chrome.png
  gemini/screens/datepicker/layout/default/chrome.png
  gemini/tests/set1/datepicker.js
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
  src/dev/src/app/datepicker/datepicker.demo.html
  src/dev/src/app/datepicker/datepicker.demo.module.ts
  src/dev/src/app/datepicker/datepicker.demo.routing.ts
  src/dev/src/app/datepicker/layout.html
  src/dev/src/app/datepicker/layout.ts
  src/dev/src/app/datepicker/ngmodel-wrapper-explicit-wrapper.html
Labels: Bug, PR Target: Master & Patch

#2735 [NG] support reset and forced validation
  golden/clr-angular.d.ts
  src/clr-angular/forms/checkbox/checkbox-container.ts
  src/clr-angular/forms/checkbox/checkbox.spec.ts
  src/clr-angular/forms/checkbox/checkbox.ts
  src/clr-angular/forms/common/common.spec.ts
  src/clr-angular/forms/common/form.spec.ts
  src/clr-angular/forms/common/form.ts
  src/clr-angular/forms/common/if-error/if-error.service.spec.ts
  src/clr-angular/forms/common/if-error/if-error.service.ts
  src/clr-angular/forms/common/if-error/if-error.ts
  src/clr-angular/forms/common/providers/mark-control.service.ts
  src/clr-angular/forms/common/wrapped-control.spec.ts
  src/clr-angular/forms/common/wrapped-control.ts
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/forms/datepicker/date-input.ts
  src/clr-angular/forms/input/input-container.ts
  src/clr-angular/forms/input/input.spec.ts
  src/clr-angular/forms/input/input.ts
  src/clr-angular/forms/password/password-container.ts
  src/clr-angular/forms/password/password.spec.ts
  src/clr-angular/forms/password/password.ts
  src/clr-angular/forms/radio/radio-container.spec.ts
  src/clr-angular/forms/radio/radio-container.ts
  src/clr-angular/forms/radio/radio.spec.ts
  src/clr-angular/forms/radio/radio.ts
  src/clr-angular/forms/select/select-container.ts
  src/clr-angular/forms/select/select.spec.ts
  src/clr-angular/forms/select/select.ts
  src/clr-angular/forms/tests/container.spec.ts
  src/clr-angular/forms/tests/control.spec.ts
  src/clr-angular/forms/textarea/textarea-container.ts
  src/clr-angular/forms/textarea/textarea.spec.ts
  src/clr-angular/forms/textarea/textarea.ts
  src/dev/src/app/forms/forms.demo.module.ts
  src/dev/src/app/forms/forms.demo.routing.ts
  src/dev/src/app/forms/forms.demo.ts
  src/dev/src/app/forms/reset/reset.html
  src/dev/src/app/forms/reset/reset.ts
  tsconfig.json
Labels: Dev, Enhancement

#2805 fix(dark-theme): Selected datagrid row font color should be white
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: Dark theme, PR Target: Master & Patch

#2827 [NG] Tree view: Eager declarative case
  gemini/dark-screens/tree-view/Eager declarative tree/default/chrome.png
  gemini/dark-screens/tree-view/Tree with icons/default/chrome.png
  gemini/screens/tree-view/Eager declarative tree/default/chrome.png
  gemini/screens/tree-view/Tree with icons/default/chrome.png
  gemini/tests/set4/tree-view.js
  golden/clr-angular.d.ts
  src/clr-angular/data/tree-view/all.spec.ts
  src/clr-angular/data/tree-view/index.ts
  src/clr-angular/data/tree-view/models/selected-state.enum.ts
  src/clr-angular/data/tree-view/models/tree-node.model.spec.ts
  src/clr-angular/data/tree-view/models/tree-node.model.ts
  src/clr-angular/data/tree-view/tree-features.service.ts
  src/clr-angular/data/tree-view/tree-node.html
  src/clr-angular/data/tree-view/tree-node.spec.ts
  src/clr-angular/data/tree-view/tree-node.ts
  src/clr-angular/data/tree-view/tree-view.module.ts
  src/clr-angular/forms/styles/_checkbox.clarity.scss
  src/clr-angular/utils/expand/if-expanded.ts
  src/clr-angular/utils/expand/providers/expand.ts
  src/dev/src/app/tree-view/eager-declarative-tree/eager-declarative-tree.html
  src/dev/src/app/tree-view/eager-declarative-tree/eager-declarative-tree.ts
  src/dev/src/app/tree-view/nodes-with-icons/nodes-with-icons.html
  src/dev/src/app/tree-view/nodes-with-icons/nodes-with-icons.ts
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing-abbey-road.ts
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing-revolver.ts
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing-rubber-soul.ts
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing.html
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing.ts
  src/dev/src/app/tree-view/tree-view.demo.module.ts
  src/dev/src/app/tree-view/tree-view.demo.routing.ts
  src/dev/src/app/tree-view/tree-view.demo.ts
Labels: Bug, Dev, High

#2845 [NG] Tree view: Recursive case, both eager and lazy
  gemini/dark-screens/tree-view/Eager recursive tree/default/chrome.png
  gemini/dark-screens/tree-view/Lazy recursive tree/default/chrome.png
  gemini/screens/tree-view/Eager recursive tree/default/chrome.png
  gemini/screens/tree-view/Lazy recursive tree/default/chrome.png
  gemini/tests/set4/tree-view.js
  golden/clr-angular.d.ts
  src/clr-angular/data/tree-view/all.spec.ts
  src/clr-angular/data/tree-view/index.ts
  src/clr-angular/data/tree-view/recursive-children.spec.ts
  src/clr-angular/data/tree-view/recursive-children.ts
  src/clr-angular/data/tree-view/recursive-for-of.spec.ts
  src/clr-angular/data/tree-view/recursive-for-of.ts
  src/clr-angular/data/tree-view/tree-features.service.ts
  src/clr-angular/data/tree-view/tree-node.html
  src/clr-angular/data/tree-view/tree-node.spec.ts
  src/clr-angular/data/tree-view/tree-node.ts
  src/clr-angular/data/tree-view/tree-view.module.ts
  src/clr-angular/data/tree-view/tree.spec.ts
  src/clr-angular/data/tree-view/tree.ts
  src/clr-angular/utils/testing/helpers.spec.ts
  src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.html
  src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts
  src/dev/src/app/tree-view/lazy-recursive-tree/lazy-recursive-tree.html
  src/dev/src/app/tree-view/lazy-recursive-tree/lazy-recursive-tree.ts
  src/dev/src/app/tree-view/tree-view.demo.module.ts
  src/dev/src/app/tree-view/tree-view.demo.routing.ts
  src/dev/src/app/tree-view/tree-view.demo.ts
Labels: Bug, Dev, High

#2876 [WEB] Pretty format the alert example (v0.13, v1.0)
  latest/src/app/documentation/demos/alert/angular/alert-angular-app-level-alerts.demo.html
  v0.13/src/app/documentation/demos/alert/angular/alert-angular-app-level-alerts.demo.html
Labels: dco-required
