Repository vmware/clarity, pull requests merged in 2018-09, with the labels that each got.

#2621 [ENH] Allowing tooltips to be used inside static button groups
  CODING_GUIDELINES.md
  src/clr-angular/button/button-group/_button-group.clarity.scss
Labels: PR Target: Master & Patch

#2524 [NG] DnD final PR
  gemini/screens/iconography/selection-preview-settings/default/chrome.png
  src/app/drag-and-drop/basic-draggable.demo.html
  src/app/drag-and-drop/basic-droppable.demo.html
  src/app/drag-and-drop/basic-droppable.demo.ts
  src/app/drag-and-drop/drag-and-drop.demo.html
  src/app/drag-and-drop/drag-and-drop.demo.module.ts
  src/app/drag-and-drop/drag-and-drop.demo.routing.ts
  src/app/drag-and-drop/drag-and-drop.demo.scss
  src/app/drag-and-drop/drop-tolerance.demo.html
  src/app/drag-and-drop/drop-tolerance.demo.ts
  src/app/drag-and-drop/grouping.demo.html
  src/app/drag-and-drop/grouping.demo.ts
  src/app/iconography/iconography.demo.scss
  src/clr-angular/utils/drag-and-drop/draggable-ghost.spec.ts
  src/clr-angular/utils/drag-and-drop/droppable/droppable.ts
  src/clr-angular/utils/drag-and-drop/if-dragged.spec.ts
  src/clr-angular/utils/drag-and-drop/if-dragged.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.spec.ts
  src/clr-angular/utils/drag-and-drop/providers/drag-event-listener.ts
Labels: In Review

#2632 [NG] Datagrid: reduce the number of outputs for selection changes
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
Labels: Bug, Dev, In Review

#2645 [NG] fix index for radios and rows to be consistent
  src/clr-angular/data/datagrid/datagrid-row.ts
Labels: In Review

#2652 Correctly export CodeHighlight from UtilsModule
  latest/src/app/utils/utils.module.ts
Labels: Dev, In Review, Website

#2653 [BUILD] This adds a custom TSLint rule for us to guard against barrel imports
  .gitignore
  package.json
  src/clr-angular/button/button-group/button.spec.ts
  src/clr-angular/button/button-group/button.ts
  src/clr-angular/button/button-loading/loading-button.spec.ts
  src/clr-angular/forms/common/wrapped-control.ts
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/popover/signpost/signpost-content.spec.ts
  src/clr-angular/utils/expand/providers/expand.spec.ts
  src/clr-angular/utils/expand/providers/expand.ts
  src/dev/src/app/grid/grid.demo.module.ts
  tests/tslint/README.md
  tests/tslint/src/noBarrelImportsRule.ts
  tests/tslint/tsconfig.json
  tslint.json
Labels: In Review

#2649 [NG] Fix bug with clr-dropdown with OnPush detection strategy
  golden/clr-angular.d.ts
  src/clr-angular/popover/dropdown/dropdown.ts
Labels: In Review

#2662 [NG] Use a `providedIn: 'root'` for our i18n service
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/common.spec.ts
  src/clr-angular/providers.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
Labels: Dev, In Review, Oops

#2656 [NG] fix form controls grid override retaining col classes
  gemini/screens/input/default/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/forms/common/providers/control-class.service.spec.ts
  src/clr-angular/forms/common/providers/control-class.service.ts
  src/clr-angular/forms/input/input.ts
  src/clr-angular/forms/password/password.ts
  src/clr-angular/forms/radio/radio.ts
  src/clr-angular/forms/select/select.ts
  src/clr-angular/forms/tests/control.spec.ts
  src/clr-angular/forms/textarea/textarea.ts
  src/dev/src/app/input/input.demo.html
Labels: In Review

#2684 [ICONS] add missing hand icons from vol12
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  src/clr-icons/shapes/essential-shapes.ts
Labels: In Review
