Repository vmware/clarity, pull requests merged in 2019-06, with the labels that each got.

#3395 [DOCS] Update datepicker internationaization example
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.ts
Labels: Website

#3435 [NG] Wizard Stepnav - adding disabled attribute to button - Backport V1
  gemini/dark-screens/wizard/basic/default/chrome.png
  gemini/dark-screens/wizard/default-header-actions/default/chrome.png
  gemini/dark-screens/wizard/dynamic-wizard/default/chrome.png
  gemini/dark-screens/wizard/form-alert/default/chrome.png
  gemini/dark-screens/wizard/form-validation/default/chrome.png
  gemini/dark-screens/wizard/page-header-actions/default/chrome.png
  gemini/dark-screens/wizard/static-wizard/default/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/default-header-actions/default/chrome.png
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/screens/wizard/form-alert/default/chrome.png
  gemini/screens/wizard/form-validation/default/chrome.png
  gemini/screens/wizard/page-header-actions/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  src/clr-angular/wizard/wizard-stepnav-item.spec.ts
  src/clr-angular/wizard/wizard-stepnav-item.ts
Labels: Accessibility

#3432 [NG] Add disabled attribute to Wizard > Stepnav > Button
  gemini/dark-screens/wizard/basic/default/chrome.png
  gemini/dark-screens/wizard/default-header-actions/default/chrome.png
  gemini/dark-screens/wizard/dynamic-wizard/default/chrome.png
  gemini/dark-screens/wizard/page-header-actions/default/chrome.png
  gemini/dark-screens/wizard/static-wizard/default/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/default-header-actions/default/chrome.png
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/screens/wizard/page-header-actions/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  src/clr-angular/wizard/wizard-stepnav-item.spec.ts
  src/clr-angular/wizard/wizard-stepnav-item.ts
Labels: Accessibility, PR Target: Master & Patch

#3439 [WEB] Backport the Internationalization documentation to V1
  src/website/src/app/documentation/demos/i18n/i18n.demo.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.module.ts
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
  src/website/src/app/documentation/documentation-routing.module.ts
  src/website/src/settings/componentlist.json
Labels: Accessibility

#3434 [NG][WEB] Adding aria-label to datagrid-pagination - backport v1
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
  src/clr-angular/data/datagrid/datagrid-pagination.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/dev/src/app/i18n-a11y/common-strings.service.ts
Labels: dco-required

#3452 chore(website): Update Colins picture.
  src/website/src/assets/images/team/colin.png
Labels: Website

#3453 [WEBSITE] fix add missing robots.txt file
  angular.json
  src/website/src/robots.txt
Labels: Website

#3455 [NG] fixes modal body content keyboard scroll support
  src/clr-angular/modal/modal-body.spec.ts
  src/clr-angular/modal/modal-body.ts
  src/clr-angular/modal/modal.module.ts
Labels: PR Target: Master & Patch

#3450 ClrDropdownTrigger Angular AOT fix
  src/clr-angular/popover/dropdown/dropdown-trigger.ts
Labels: PR Target: Master & Patch

#3446 add netlify badge
  src/website/src/app/home/home.component.html
Labels: Website

#3478 Backport: Issue 3413
  src/clr-angular/modal/modal.html
  src/clr-angular/modal/modal.spec.ts
Labels: Accessibility

#3477 Modal close button needs an accessible name
  src/clr-angular/modal/modal.html
  src/clr-angular/modal/modal.spec.ts
Labels: Accessibility

#3489 [WEBSITE] fix color page
  src/website/src/app/documentation/demos/color/clipboard-copy.service.ts
  src/website/src/app/documentation/demos/color/clipboard-input.scss
  src/website/src/app/documentation/demos/color/clipboard-input.ts
  src/website/src/app/documentation/demos/color/color-palette-functional.demo.html
  src/website/src/app/documentation/demos/color/color-palette-functional.ts
  src/website/src/app/documentation/demos/color/color-palette-functional/color-palette-functional.demo.html
  src/website/src/app/documentation/demos/color/color-palette-functional/color-palette-functional.demo.scss
  src/website/src/app/documentation/demos/color/color-palette-functional/color-palette-functional.demo.ts
  src/website/src/app/documentation/demos/color/color-palette-functional/functional-color-palettes.ts
  src/website/src/app/documentation/demos/color/color-palette.ts
  src/website/src/app/documentation/demos/color/color-palette/color-palette.demo.html
  src/website/src/app/documentation/demos/color/color-palette/color-palette.demo.scss
  src/website/src/app/documentation/demos/color/color-palette/color-palette.demo.ts
  src/website/src/app/documentation/demos/color/color-palette/color-palettes.ts
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme-donut.demo.html
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme-donut.demo.scss
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme-donut.demo.ts
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme.demo.html
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme.demo.scss
  src/website/src/app/documentation/demos/color/color-scheme/color-scheme.demo.ts
  src/website/src/app/documentation/demos/color/color-scheme/color-schemes.ts
  src/website/src/app/documentation/demos/color/color.demo.html
  src/website/src/app/documentation/demos/color/color.demo.module.ts
  src/website/src/app/documentation/demos/color/color.demo.ts
  src/website/src/styles/components.scss
Labels: Website

#3507 [NG] Update button labels for datagrid-column-toggle
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.ts
Labels: Accessibility, Enhancement, PR Target: Master & Patch

#3513 [ng] fix(datepicker): Add HostListener for the datepicker toggle button
  golden/clr-angular.d.ts
  src/clr-angular/forms/datepicker/date-container.spec.ts
  src/clr-angular/forms/datepicker/date-container.ts
Labels: Accessibility, PR Target: Master & Patch

#3512 [WEBSITE] fixes resource links
  src/website/src/environments/environment.prod.ts
  src/website/src/releases/2.x/2.0.0.html
Labels: Website

#3524 [ng] fix(datepicker): Add HostListener to focus on the datepicker toggle button
  golden/clr-angular.d.ts
  src/clr-angular/forms/datepicker/date-container.spec.ts
  src/clr-angular/forms/datepicker/date-container.ts
Labels: Accessibility

#3481 Datagrid focus management (#3370)
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
  src/clr-angular/data/datagrid/datagrid-action-overflow.ts
  src/clr-angular/data/datagrid/datagrid-filter.spec.ts
  src/clr-angular/data/datagrid/datagrid-filter.ts
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.ts
Labels: Accessibility, PR Target: Master & Patch
