Repository vmware/clarity, pull requests merged in 2019-10, with the labels that each got.

#3859 fix: datagrid custom filter for 2nd column doesn't work
  src/clr-angular/data/datagrid/providers/filters.spec.ts
  src/clr-angular/data/datagrid/providers/filters.ts
Labels: component: datagrid, target: master & n-1, type: bug

#3867 fix(website): add padding-right to responsive footer
  src/website/src/app/home/home.component.scss
Labels: target: master

#3869 docs: remove duplicated section
  CODING_GUIDELINES.md
Labels: target: master

#3797 feat(datagrid): add detail pane
  cypress/integration/datagrid.js
  cypress/integration/spec.js
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
  src/clr-angular/data/datagrid/_variables.datagrid.scss
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
  src/clr-angular/data/datagrid/datagrid-detail-body.spec.ts
  src/clr-angular/data/datagrid/datagrid-detail-body.ts
  src/clr-angular/data/datagrid/datagrid-detail-header.spec.ts
  src/clr-angular/data/datagrid/datagrid-detail-header.ts
  src/clr-angular/data/datagrid/datagrid-detail.spec.ts
  src/clr-angular/data/datagrid/datagrid-detail.ts
  src/clr-angular/data/datagrid/datagrid-footer.spec.ts
  src/clr-angular/data/datagrid/datagrid-footer.ts
  src/clr-angular/data/datagrid/datagrid-hideable-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-if-detail.spec.ts
  src/clr-angular/data/datagrid/datagrid-if-detail.ts
  src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
  src/clr-angular/data/datagrid/datagrid-pagination.ts
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid-row.ts
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.module.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/helpers.spec.ts
  src/clr-angular/data/datagrid/index.ts
  src/clr-angular/data/datagrid/providers/columns.service.spec.ts
  src/clr-angular/data/datagrid/providers/columns.service.ts
  src/clr-angular/data/datagrid/providers/datagrid-detail-registerer.spec.ts
  src/clr-angular/data/datagrid/providers/detail.service.spec.ts
  src/clr-angular/data/datagrid/providers/detail.service.ts
  src/clr-angular/data/datagrid/providers/global-expandable-rows.ts
  src/clr-angular/data/datagrid/providers/table-size.service.spec.ts
  src/clr-angular/data/datagrid/render/header-renderer.spec.ts
  src/clr-angular/data/datagrid/render/main-renderer.spec.ts
  src/clr-angular/data/datagrid/render/main-renderer.ts
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/utils/i18n/common-strings.default.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/dev/src/app/datagrid/datagrid.demo.html
  src/dev/src/app/datagrid/datagrid.demo.module.ts
  src/dev/src/app/datagrid/datagrid.demo.routing.ts
  src/dev/src/app/datagrid/detail/detail.html
  src/dev/src/app/datagrid/detail/detail.ts
Labels: target: master

#3875 fix: remove max-height from `pre`
  src/clr-angular/typography/_code.clarity.scss
  src/website/src/app/utils/code-snippet.ts
Labels: Breaking Change, target: master

#3842 feat(wizard): wizard step error state
  gemini/dark-screens/wizard/basic/default/chrome.png
  gemini/dark-screens/wizard/custom-danger-button/default/chrome.png
  gemini/dark-screens/wizard/default-header-actions/default/chrome.png
  gemini/dark-screens/wizard/dynamic-wizard/default/chrome.png
  gemini/dark-screens/wizard/lastpage/default/chrome.png
  gemini/dark-screens/wizard/page-header-actions/default/chrome.png
  gemini/dark-screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/dark-screens/wizard/static-wizard/default/chrome.png
  gemini/dark-screens/wizard/step-error/default/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/custom-danger-button/default/chrome.png
  gemini/screens/wizard/default-header-actions/default/chrome.png
  gemini/screens/wizard/dynamic-wizard/default/chrome.png
  gemini/screens/wizard/lastpage/default/chrome.png
  gemini/screens/wizard/page-header-actions/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  gemini/screens/wizard/step-error/default/chrome.png
  gemini/tests/set4/wizard.js
  golden/clr-angular.d.ts
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/wizard/_variables.wizard.scss
  src/clr-angular/wizard/_wizard.clarity.scss
  src/clr-angular/wizard/wizard-page.ts
  src/clr-angular/wizard/wizard-stepnav-item.ts
  src/clr-angular/wizard/wizard-stepnav.ts
  src/clr-angular/wizard/wizard.spec.ts
  src/dev/src/app/wizard/wizard-step-error.demo.html
  src/dev/src/app/wizard/wizard-step-error.demo.ts
  src/dev/src/app/wizard/wizard.demo.module.ts
  src/dev/src/app/wizard/wizard.demo.routing.ts
  src/dev/src/app/wizard/wizard.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard.demo.html
Labels: status: ready to merge, target: master

#3851 feat: a11y and focus management for tree-view
  gemini/dark-screens/tree-view/Tree with icons/default/chrome.png
  gemini/screens/tree-view/Tree with icons/default/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/data/tree-view/_tree-view.clarity.scss
  src/clr-angular/data/tree-view/all.spec.ts
  src/clr-angular/data/tree-view/models/tree-node.model.ts
  src/clr-angular/data/tree-view/recursive-children.ts
  src/clr-angular/data/tree-view/tree-focus-manager.service.spec.ts
  src/clr-angular/data/tree-view/tree-focus-manager.service.ts
  src/clr-angular/data/tree-view/tree-node-link.ts
  src/clr-angular/data/tree-view/tree-node.html
  src/clr-angular/data/tree-view/tree-node.spec.ts
  src/clr-angular/data/tree-view/tree-node.ts
  src/clr-angular/data/tree-view/tree-view.module.ts
  src/clr-angular/data/tree-view/tree.spec.ts
  src/clr-angular/data/tree-view/tree.ts
  src/clr-angular/layout/main-container/_layout.clarity.scss
  src/clr-angular/utils/focus/key-focus/util.ts
  src/dev/src/app/tree-view/eager-declarative-tree/eager-declarative-tree.html
  src/dev/src/app/tree-view/nodes-with-icons/nodes-with-icons.html
  src/dev/src/app/tree-view/nodes-with-icons/nodes-with-icons.ts
  src/dev/src/app/tree-view/pre-selection/pre-selection.html
  src/dev/src/app/tree-view/tree-node-routing/tree-node-routing.html
  src/website/src/app/documentation/demos/tree-view/basic-tree-DM/tree-basic-DM.html
  src/website/src/app/documentation/demos/tree-view/basic-tree-DM/tree-basic-DM.ts
  src/website/src/app/documentation/demos/tree-view/basic-tree/tree-basic.html
  src/website/src/app/documentation/demos/tree-view/boolean-selection-tree/boolean-selection-tree.html
  src/website/src/app/documentation/demos/tree-view/boolean-selection-tree/boolean-selection-tree.ts
  src/website/src/app/documentation/demos/tree-view/label-change-on-expand/label-change-on-expand.html
  src/website/src/app/documentation/demos/tree-view/label-change-on-expand/label-change-on-expand.ts
  src/website/src/app/documentation/demos/tree-view/small-selection-tree/small-selection-tree.html
  src/website/src/app/documentation/demos/tree-view/tree-node-routing/tree-node-routing.html
  src/website/src/app/documentation/demos/tree-view/tree-node-routing/tree-node-routing.ts
  src/website/src/app/documentation/demos/tree-view/tree-view-dynamic/tree-view-dynamic.html
  src/website/src/app/documentation/demos/tree-view/tree-view-dynamic/tree-view-dynamic.ts
  src/website/src/app/documentation/documentation.component.ts
Labels: needs: accessibility input, target: master, type: accessibility

#3888 fix: website regression
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.scss
Labels: Regression, status: ready to merge

#3749 feat(datagrid): disable single or multi rows from selection
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid-row.spec.ts
  src/clr-angular/data/datagrid/datagrid-row.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
  src/dev/src/app/datagrid/conditional-selection/conditional-selection.html
  src/dev/src/app/datagrid/conditional-selection/conditional-selection.ts
  src/dev/src/app/datagrid/datagrid.demo.html
  src/dev/src/app/datagrid/datagrid.demo.module.ts
  src/dev/src/app/datagrid/datagrid.demo.routing.ts
  src/dev/src/app/datagrid/selection-row-mode/selection-row-mode.html
  src/website/src/app/documentation/demos/datagrid/selection/selection.html
  src/website/src/app/documentation/demos/datagrid/selection/selection.ts
  src/website/src/app/documentation/demos/datagrid/single-selection/single-selection.html
  src/website/src/app/documentation/demos/datagrid/single-selection/single-selection.ts
Labels: target: master, type: enhancement

#3896 fix: update clr-angular.d.ts
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
Labels: type: bug

#3886 Topic/bundle tests
  bundlesize.json
  package-lock.json
  package.json
  src/clr-core/styles/global.scss
Labels: status: ready to merge

#3887 feat(datagrid): preserve selection while filtering
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
  src/dev/src/app/datagrid/preserve-selection/preserve-selection.html
  src/dev/src/app/datagrid/preserve-selection/preserve-selection.ts
  src/website/src/app/documentation/demos/datagrid/selection/selection.html
Labels: status: ready to merge, target: master & n-1

#3866 fix(datagrid): align column header vertically
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: status: ready to merge, target: master & n-1

#3750 fix(tabs): extra spacing between tab and tab content in ie 11
  src/clr-angular/layout/tabs/_tabs.clarity.scss
Labels: status: ready to merge, target: master & n-1

#3901 fix(datagrid): toggling sorting icon
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
Labels: component: datagrid, target: master & n-1

#3924 fix: removes unnecessary text from the mobile header title
  src/website/src/styles/code.scss
Labels: status: ready to merge, target: master

#3921 feat: adding equilateral sass mixins
  src/clr-angular/accordion/_accordion.clarity.scss
  src/clr-angular/button/button-group/_button-group.clarity.scss
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
  src/clr-angular/data/stack-view/_stack-view.clarity.scss
  src/clr-angular/data/tree-view/_tree-view.clarity.scss
  src/clr-angular/emphasis/alert/_alert.clarity.scss
  src/clr-angular/forms/combobox/_combobox.clarity.scss
  src/clr-angular/forms/datepicker/_datepicker.clarity.scss
  src/clr-angular/forms/styles/_containers.clarity.scss
  src/clr-angular/forms/styles/_file.clarity.scss
  src/clr-angular/forms/styles/_mixins.forms.scss
  src/clr-angular/forms/styles/_select.clarity.scss
  src/clr-angular/forms/styles/_toggles.clarity.scss
  src/clr-angular/image/_images.clarity.scss
  src/clr-angular/layout/_card.clarity.scss
  src/clr-angular/layout/_login.clarity.scss
  src/clr-angular/layout/nav/_header.clarity.scss
  src/clr-angular/layout/nav/_responsive-nav.clarity.scss
  src/clr-angular/layout/nav/_sidenav.clarity.scss
  src/clr-angular/layout/vertical-nav/_vertical-nav.clarity.scss
  src/clr-angular/modal/_modal.clarity.scss
  src/clr-angular/popover/dropdown/_dropdown.clarity.scss
  src/clr-angular/popover/signpost/_signposts.clarity.scss
  src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
  src/clr-angular/progress/spinner/_spinner.clarity.scss
  src/clr-angular/timeline/_timeline.clarity.scss
  src/clr-angular/utils/_mixins.clarity.scss
  src/clr-angular/wizard/_wizard.clarity.scss
Labels: status: ready to merge

#3898 test(wizard): tests for step error state
  src/clr-angular/wizard/wizard-page.mock.ts
  src/clr-angular/wizard/wizard-page.spec.ts
  src/clr-angular/wizard/wizard-stepnav-item.spec.ts
Labels: component: wizard, status: ready to merge

#3941 fix(select): add select option font color
  cypress/integration/select.js
  cypress/integration/spec.js
  src/clr-angular/utils/_theme.dark.clarity.scss
Labels: component: forms, flag: regression

#3939 fix: website is missing code-highlight utils module for navigation page
  src/website/src/app/documentation/demos/nav/nav.demo.module.ts
Labels: priority: low, status: ready to merge, type: website
