Repository vmware/clarity, pull requests merged in 2019-05, with the labels that each got.

#3329 [NG] Lifecycle fix for tabs templating initialization (#3273)
  golden/clr-angular.d.ts
  src/clr-angular/layout/tabs/providers/tabs.service.ts
  src/clr-angular/layout/tabs/tab-content.spec.ts
  src/clr-angular/layout/tabs/tab-content.ts
  src/clr-angular/layout/tabs/tab.spec.ts
  src/clr-angular/layout/tabs/tabs.spec.ts
  src/clr-angular/layout/tabs/tabs.ts
Labels: dco-required

#3347 [NG] fix(datagrid-filter): Removes filter icon svg from scss
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
  src/clr-angular/data/datagrid/datagrid-filter.ts
  src/clr-angular/image/_icons.clarity.scss
Labels: Browser: Edge, Browser: IE, Bug

#3345 [DOCS] fix(latest): Corrects a typo in the docs.
  src/website/src/app/documentation/demos/toggles/toggles.demo.html
Labels: Website

#3340 [CORE] fix: Removes artifacts from travis config
  .travis.yml
Labels: Build

#3359 core: Upgrade dependencies for Clarity v2.0.0-rc.2
  package-lock.json
  package.json
Labels: Chore

#3357 [WEB] Add example for fixed-height datagrid
  src/website/src/app/documentation/demos/datagrid/datagrid.demo.module.ts
  src/website/src/app/documentation/demos/datagrid/datagrid.demo.scss
  src/website/src/app/documentation/demos/datagrid/fixed-height/fixed-height.html
  src/website/src/app/documentation/demos/datagrid/fixed-height/fixed-height.ts
Labels: dco-required

#3283 [ng] Accessible dropdown
  gemini/dark-screens/dropdown/angular-nested/clicked/chrome.png
  gemini/dark-screens/dropdown/angular-nested/submenu-left/chrome.png
  gemini/dark-screens/dropdown/angular-nested/submenu-right/chrome.png
  gemini/dark-screens/dropdown/angular-positioning/if-open-clicked/chrome.png
  gemini/dark-screens/dropdown/angular-positioning/no-if-open-clicked/chrome.png
  gemini/dark-screens/dropdown/dropdown-header/click the dropdown toggle/chrome.png
  gemini/dark-screens/navigation/header-types/header-dropdown/chrome.png
  gemini/screens/dropdown/angular-nested/clicked/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-left/chrome.png
  gemini/screens/dropdown/angular-nested/submenu-right/chrome.png
  gemini/screens/dropdown/angular-positioning/if-open-clicked/chrome.png
  gemini/screens/dropdown/angular-positioning/no-if-open-clicked/chrome.png
  gemini/screens/dropdown/dropdown-header/click the dropdown toggle/chrome.png
  gemini/screens/navigation/header-types/header-dropdown/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/popover/dropdown/_menu-mixins.clarity.scss
  src/clr-angular/popover/dropdown/all.spec.ts
  src/clr-angular/popover/dropdown/dropdown-item.spec.ts
  src/clr-angular/popover/dropdown/dropdown-item.ts
  src/clr-angular/popover/dropdown/dropdown-menu.spec.ts
  src/clr-angular/popover/dropdown/dropdown-menu.ts
  src/clr-angular/popover/dropdown/dropdown-trigger.spec.ts
  src/clr-angular/popover/dropdown/dropdown-trigger.ts
  src/clr-angular/popover/dropdown/dropdown.spec.ts
  src/clr-angular/popover/dropdown/dropdown.ts
  src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
  src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.spec.ts
  src/clr-angular/utils/focus/all.spec.ts
  src/clr-angular/utils/focus/arrow-key-direction.enum.ts
  src/clr-angular/utils/focus/focus.service.spec.ts
  src/clr-angular/utils/focus/focus.service.ts
  src/clr-angular/utils/focus/focusable-item/basic-focusable-item.service.ts
  src/clr-angular/utils/focus/focusable-item/basic-focusable-item.spec.ts
  src/clr-angular/utils/focus/focusable-item/custom-focusable-item-provider.ts
  src/clr-angular/utils/focus/focusable-item/focusable-item.mock.ts
  src/clr-angular/utils/focus/focusable-item/focusable-item.ts
  src/clr-angular/utils/focus/focusable-item/linkers.spec.ts
  src/clr-angular/utils/focus/focusable-item/linkers.ts
  src/clr-angular/utils/focus/wrap-observable.spec.ts
  src/clr-angular/utils/focus/wrap-observable.ts
  src/clr-angular/utils/testing/helpers.spec.ts
  src/dev/src/app/dropdown/dropdown-angular-nested.demo.html
  src/dev/src/app/dropdown/dropdown-angular-positioning.demo.html
  src/dev/src/app/nav/header-types.demo.html
  src/website/src/app/documentation/demos/dropdown/dropdown.demo.html
Labels: Accessibility

#3360 Create an API docs page, generated automatically
  .compodocrc.json
  netlify.toml
  package-lock.json
  package.json
  tsconfig.api-docs.json
Labels: Website

#3384 [NG] Adding aria-label to clr-dg-column button.
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Labels: PR Target: Master & Patch
