Repository vmware/clarity, pull requests merged in 2019-09, with the labels that each got.

#3705 docs: update documentation
  BUILD.md
  CODING_GUIDELINES.md
  CONTRIBUTING.md
  DEVELOPMENT_CONTRIBUTION.md
  FAQ.md
Labels: type: website

#3694 docs: updating documentation language
  src/website/src/app/documentation/demos/grid/grid.demo.html
  src/website/src/app/documentation/demos/toggles/toggles.demo.html
Labels: PR Target: Master & Patch

#3784 docs: fix typos in website's pages
  src/website/src/app/documentation/demos/alert/alerts.demo.html
  src/website/src/app/documentation/demos/button-group/button-group.demo.html
  src/website/src/app/documentation/demos/datagrid/built-in-filters/built-in-filters.html
  src/website/src/app/documentation/demos/datagrid/filtering/filtering.html
  src/website/src/app/documentation/demos/datagrid/fixed-height/fixed-height.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-internationalization.demo.html
  src/website/src/app/documentation/demos/dropdown/dropdown.demo.html
  src/website/src/app/documentation/demos/header/header.demo.html
  src/website/src/app/documentation/demos/input/input.demo.html
  src/website/src/app/documentation/demos/labels/labels-with-badges.demo.html
  src/website/src/app/documentation/demos/labels/labels.demo.html
  src/website/src/app/documentation/demos/password/password.demo.html
  src/website/src/app/documentation/demos/radio/radio.demo.html
  src/website/src/app/documentation/demos/select/select.demo.html
  src/website/src/app/documentation/demos/sidenav/sidenav.demo.html
  src/website/src/app/documentation/demos/signposts/signpost.demo.html
  src/website/src/app/documentation/demos/textarea/textarea.demo.html
  src/website/src/app/documentation/demos/themes/themes.demo.html
  src/website/src/app/documentation/demos/timeline/timeline-full-demo.component.html
  src/website/src/app/documentation/demos/timeline/timeline.demo.html
  src/website/src/app/documentation/demos/wizard/wizard.demo.html
Labels: type: website

#3783 docs: fix typos in markdown documents
  CODING_GUIDELINES.md
  CONTRIBUTING.md
  DESIGN_CONTRIBUTION.md
Labels: type: website

#3790 fix(a11y): changing color of yellow icons for a11y
  gemini/dark-screens/iconography/color-options/default/chrome.png
  gemini/dark-screens/iconography/selection-commerce-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-commerce-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-core-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-core-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-media-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-media-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-social-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-social-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/color-options/default/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-commerce-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-core-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-media-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-media-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-social-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-social-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  src/clr-icons/clr-icons.scss
Labels: Accessibility, Backport, PR Target: Master & Patch

#3774 fix(signpost): fix signpost focus management
  gemini/dark-screens/signposts/bottom-left/chrome.png
  gemini/dark-screens/signposts/bottom-middle/chrome.png
  gemini/dark-screens/signposts/bottom-right/chrome.png
  gemini/dark-screens/signposts/default/chrome.png
  gemini/dark-screens/signposts/left-bottom/chrome.png
  gemini/dark-screens/signposts/left-middle/chrome.png
  gemini/dark-screens/signposts/left-top/chrome.png
  gemini/dark-screens/signposts/right-bottom/chrome.png
  gemini/dark-screens/signposts/right-middle/chrome.png
  gemini/dark-screens/signposts/right-top/chrome.png
  gemini/dark-screens/signposts/top-middle/chrome.png
  gemini/dark-screens/signposts/top-right/chrome.png
  gemini/screens/signposts/bottom-left/chrome.png
  gemini/screens/signposts/bottom-middle/chrome.png
  gemini/screens/signposts/bottom-right/chrome.png
  gemini/screens/signposts/default/chrome.png
  gemini/screens/signposts/left-bottom/chrome.png
  gemini/screens/signposts/left-middle/chrome.png
  gemini/screens/signposts/left-top/chrome.png
  gemini/screens/signposts/right-bottom/chrome.png
  gemini/screens/signposts/right-middle/chrome.png
  gemini/screens/signposts/right-top/chrome.png
  gemini/screens/signposts/top-middle/chrome.png
  gemini/screens/signposts/top-right/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/popover/signpost/all.spec.ts
  src/clr-angular/popover/signpost/providers/signpost-focus-manager.service.spec.ts
  src/clr-angular/popover/signpost/providers/signpost-focus-manager.service.ts
  src/clr-angular/popover/signpost/signpost-content.spec.ts
  src/clr-angular/popover/signpost/signpost-content.ts
  src/clr-angular/popover/signpost/signpost-trigger.spec.ts
  src/clr-angular/popover/signpost/signpost-trigger.ts
  src/clr-angular/popover/signpost/signpost.module.ts
  src/clr-angular/popover/signpost/signpost.spec.ts
  src/clr-angular/popover/signpost/signpost.ts
Labels: Backport, PR Target: Master & Patch

#3733 fix: keep consistent height if signpost in datagrid header
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
Labels: PR Target: Master & Patch

#3805 docs(alert): a11y warning against use of actions inside dynamic alerts
  src/website/src/app/documentation/demos/alert/alerts.demo.html
Labels: PR Target: Master & Patch

#3809 fix: missing icons for internet explorer
  angular.json
  src/website/src/polyfills.ts
Labels: status: ready to merge, target: n-1 or n-2, type: bug

#3816 fix(signpost): use default cursor in popover
  src/clr-angular/popover/signpost/_signposts.clarity.scss
Labels: target: master & n-1

#3808 fix: on website input grouping heading overlaps example
  src/website/src/app/documentation/demos/timeline/timeline.demo.html
  src/website/src/styles/components.scss
Labels: status: ready to merge, target: master & n-1, type: bug, type: website

#3818 fix(wizard): wizard title gets double focus attempts
  commitlint.config.js
  gemini/dark-screens/wizard/custom-danger-button/default/chrome.png
  gemini/dark-screens/wizard/lastpage/default/chrome.png
  gemini/dark-screens/wizard/page-header-actions/default/chrome.png
  gemini/dark-screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/custom-danger-button/default/chrome.png
  gemini/screens/wizard/lastpage/default/chrome.png
  gemini/screens/wizard/page-header-actions/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  src/clr-angular/wizard/_wizard.clarity.scss
  src/clr-angular/wizard/wizard.html
Labels: status: ready to merge, target: master & n-2

#3819 fix: download links don't indicate their purpose
  src/website/src/releases/final-template/news-template.html
Labels: target: master

#3780 fix(header): icons in header documentation
  gemini/dark-screens/navigation/header-types/default/chrome.png
  gemini/dark-screens/navigation/header-types/header-dropdown/chrome.png
  gemini/screens/navigation/header-types/header-dropdown/chrome.png
  src/website/src/app/documentation/demos/header/header-types.demo.html
  src/website/src/app/documentation/demos/header/header-types.ts
Labels: Accessibility, status: ready to merge, target: master & n-1

#3817 fix(icons): icon colors do not match clr-ui dark mode colors
  gemini/dark-screens/dropdown/multi-click/default/chrome.png
  gemini/dark-screens/iconography/color-options/default/chrome.png
  gemini/dark-screens/iconography/variants/default/chrome.png
  gemini/dark-screens/tabs/angular/overflowing/chrome.png
  gemini/dark-screens/tabs/static/default/chrome.png
  src/clr-angular/dark-theme.scss
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/utils/_theme.dark.icons.clarity.scss
Labels: component: icons

#3831 docs(progress-bar): update docs and deprecate for removal
  src/clr-angular/forms/common/control-containers.ts
  src/clr-angular/progress/progress-bars/_progress-bars.clarity.scss
  src/clr-angular/progress/progress-bars/_variables.progress-bars.scss
  src/clr-angular/progress/progress-bars/progress-bar.ts
  src/website/src/app/documentation/demos/progress-bars/progbar-example.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bar-animations.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bar-colors.html
  src/website/src/app/documentation/demos/progress-bars/progress-bar-colors.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bar-component.demo.html
  src/website/src/app/documentation/demos/progress-bars/progress-bar-story.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.html
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.module.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.scss
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.ts
  src/website/src/app/documentation/documentation.component.ts
Labels: target: master

#3826 fix(stack-view): a11y add aria-controls to stack-view
  golden/clr-angular.d.ts
  src/clr-angular/data/stack-view/stack-block.spec.ts
  src/clr-angular/data/stack-view/stack-block.ts
Labels: status: ready to merge, target: master & n-2

#3838 fix: icon colors do not match clr-ui dark mode colors (hsl)
  gemini/dark-screens/dropdown/multi-click/default/chrome.png
  gemini/dark-screens/iconography/color-options/default/chrome.png
  gemini/dark-screens/iconography/variants/default/chrome.png
  gemini/dark-screens/tabs/angular/overflowing/chrome.png
  gemini/dark-screens/tabs/angular/vertical-hover/chrome.png
  gemini/dark-screens/tabs/static/default/chrome.png
  src/clr-angular/dark-theme.scss
  src/clr-angular/utils/_theme.dark.clarity.scss
  src/clr-angular/utils/_theme.dark.icons.clarity.scss
Labels: component: icons, dco-required, status: ready to merge, target: master

#3846 fix(stack-view): stack view async loading
  src/dev/src/app/stack-view/stack-view-angular-lazyload.html
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.html
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.ts
Labels: status: ready to merge, target: master, type: website

#3850 fix(icons): could not add new icons with capital letters for shapeName
  DEVELOPMENT_CONTRIBUTION.md
  angular.json
  commitlint.config.js
  package.json
  src/clr-icons/clr-icons-api.ts
  src/clr-icons/clr-icons.spec.ts
  src/clr-icons/karma.conf.js
  src/clr-icons/test.ts
  src/clr-icons/tsconfig.spec.json
  src/website/src/app/icons/icons-api/icons-api.component.html
Labels: component: icons, target: master

#3830 fix: form a11y
  golden/clr-angular.d.ts
  src/clr-angular/deprecations.spec.ts
  src/clr-angular/forms/common/all.spec.ts
  src/clr-angular/forms/common/form.spec.ts
  src/clr-angular/forms/common/form.ts
  src/clr-angular/forms/common/label.spec.ts
  src/clr-angular/forms/common/label.ts
  src/clr-angular/utils/i18n/common-strings.default.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/dev/src/app/forms/a11y/a11y.html
  src/dev/src/app/forms/a11y/a11y.ts
  src/dev/src/app/forms/forms.demo.module.ts
  src/dev/src/app/forms/forms.demo.routing.ts
  src/dev/src/app/forms/forms.demo.ts
  src/website/src/app/documentation/demos/checkboxes/checkboxes.demo.html
  src/website/src/app/documentation/demos/checkboxes/ng/basic.html
  src/website/src/app/documentation/demos/checkboxes/ng/label.html
  src/website/src/app/documentation/demos/checkboxes/ui/basic.html
  src/website/src/app/documentation/demos/datepicker/datepicker.demo.html
  src/website/src/app/documentation/demos/forms/forms.demo.html
  src/website/src/app/documentation/demos/forms/forms.demo.ts
  src/website/src/app/documentation/demos/forms/ng/reset.txt
  src/website/src/app/documentation/demos/forms/ng/validate.txt
  src/website/src/app/documentation/demos/input/input.demo.html
  src/website/src/app/documentation/demos/password/password.demo.html
  src/website/src/app/documentation/demos/radio/radio.demo.html
  src/website/src/app/documentation/demos/select/select.demo.html
  src/website/src/app/documentation/demos/textarea/textarea.demo.html
  src/website/src/app/documentation/demos/toggles/ng/label.html
  src/website/src/app/documentation/demos/toggles/toggles.demo.html
  src/website/src/app/documentation/demos/toggles/ui/basic.html
Labels: target: master
