Repository vmware/clarity, pull requests merged in 2019-02, with the labels that each got.

#3099 [WIP] Vol14 icons
  gemini/dark-screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid/chrome.png
  src/clr-icons/shapes/chart-shapes.ts
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
Labels: Icons

#3133 [NG] fix missing pointer style
  src/clr-angular/utils/_helpers.clarity.scss
Labels: PR Target: Master & Patch

#3141 [NG] fix missing pointer style (#3133)
  src/clr-angular/utils/_helpers.clarity.scss
Labels: dco-required

#3137 update website content for toggles, date picker, and forms
  src/website/src/app/documentation/demos/datepicker/datepicker.demo.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-api.demo.ts
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-date-io.demo.ts
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-enUS.demo.ts
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-fr.demo.ts
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-reactive-forms.ts
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-template-driven-forms.html
  src/website/src/app/documentation/demos/datepicker/demos/datepicker-template-driven-forms.ts
  src/website/src/app/documentation/demos/forms/forms.demo.html
  src/website/src/app/documentation/demos/forms/forms.demo.ts
  src/website/src/app/documentation/demos/forms/ng/optional.html
  src/website/src/app/documentation/demos/toggles/toggles.demo.html
Labels: PR Target: Master & Patch

#3127 [WEB] Remove duplicate closing bracket on code tags
  src/website/src/app/documentation/demos/wizard/wizard.demo.html
Labels: PR Target: Master & Patch

#3123 Correct typo in modal body
  src/website/src/app/documentation/demos/modal/modal-animation-design.demo.html
Labels: PR Target: Master & Patch

#3117 [NG] fix DataGrid clearSelection for SingleSelect mode
  src/clr-angular/data/datagrid/providers/selection.spec.ts
  src/clr-angular/data/datagrid/providers/selection.ts
Labels: Bug, Dev, PR Target: Master & Patch

#3135 [NG] fix a11y issue password input
  src/clr-angular/forms/password/password-container.spec.ts
  src/clr-angular/forms/password/password-container.ts
  src/clr-angular/forms/styles/_input-group.clarity.scss
  src/dev/src/app/forms/input-group/input-group.html
  src/dev/src/app/forms/input-group/input-group.ts
Labels: PR Target: Master & Patch, dco-required
