Repository vmware/clarity, pull requests merged in 2019-03, with the labels that each got.

#3148 [NG] fix a11y issue password input (#3135)
  src/clr-angular/forms/password/password-container.spec.ts
  src/clr-angular/forms/password/password-container.ts
  src/clr-angular/forms/styles/_input-group.clarity.scss
  src/dev/src/app/forms/input-group/input-group.html
  src/dev/src/app/forms/input-group/input-group.ts
Labels: dco-required

#3136 [NG] fix button title for button group
  golden/clr-angular.d.ts
  src/clr-angular/button/button-group/button.spec.ts
  src/clr-angular/button/button-group/button.ts
Labels: PR Target: Master & Patch, dco-required

#3151 (v1 backport) [NG] fix button title for button group (#3136)
  golden/clr-angular.d.ts
  src/clr-angular/button/button-group/button.spec.ts
  src/clr-angular/button/button-group/button.ts
Labels: dco-required

#3171 feat(schematics) automatically support installing @next
  src/schematics/README.md
  src/schematics/src/add/index.ts
Labels: PR Target: Master & Patch

#3159 [NG] datepicker event fix
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
Labels: PR Target: Master & Patch

#3152 fix(datagrid): adds sort button icon to datagrid-column
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/_datagrid.clarity.scss
  src/clr-angular/data/datagrid/datagrid-column.spec.ts
  src/clr-angular/data/datagrid/datagrid-column.ts
  src/clr-angular/image/_icons.clarity.scss
Labels: PR Target: Master & Patch

#3175 [NG] Fix pagination init lifecycle
  src/clr-angular/data/datagrid/all.spec.ts
  src/clr-angular/data/datagrid/datagrid-pagination.integration.spec.ts
  src/clr-angular/data/datagrid/datagrid-pagination.ts
  src/clr-angular/data/datagrid/providers/items.spec.ts
  src/clr-angular/data/datagrid/providers/items.ts
  src/clr-angular/data/datagrid/providers/page.ts
Labels: Bug, Dev, High, Oops, PR Target: Master & Patch

#3190 [NG] fix button issue for datagrid pagination
  src/clr-angular/data/datagrid/datagrid-pagination.spec.ts
  src/clr-angular/data/datagrid/datagrid-pagination.ts
Labels: PR Target: Master & Patch

#3208 [web] removed no longer valid documentation part in icons get started
  src/website/src/app/icons/icons-get-started/icons-get-started.component.html
  src/website/src/app/icons/icons-get-started/icons-get-started.component.ts
Labels: Website

#3102 [NG] Vertical tabs (#2856)
  gemini/dark-screens/tabs/angular/default/chrome.png
  gemini/dark-screens/tabs/angular/overflowing/chrome.png
  gemini/dark-screens/tabs/angular/vertical-hover/chrome.png
  gemini/dark-screens/tabs/static/default/chrome.png
  gemini/screens/tabs/angular/default/chrome.png
  gemini/screens/tabs/angular/overflowing/chrome.png
  gemini/screens/tabs/angular/vertical-hover/chrome.png
  gemini/screens/tabs/static/default/chrome.png
  gemini/tests/set4/tabs.js
  golden/clr-angular.d.ts
  src/clr-angular/forms/common/layout.spec.ts
  src/clr-angular/forms/common/layout.ts
  src/clr-angular/layout/tabs/_tabs.clarity.scss
  src/clr-angular/layout/tabs/enums/tabs-layout.enum.ts
  src/clr-angular/layout/tabs/providers/tabs.service.ts
  src/clr-angular/layout/tabs/tab-link.directive.spec.ts
  src/clr-angular/layout/tabs/tab-link.directive.ts
  src/clr-angular/layout/tabs/tabs.spec.ts
  src/clr-angular/layout/tabs/tabs.ts
  src/dev/src/app/tabs/tabs-angular.demo.html
  src/dev/src/app/tabs/tabs-angular.ts
  src/dev/src/app/tabs/tabs-static.demo.html
  src/dev/src/app/tabs/tabs.demo.scss
  src/ks-app/src/app/containers/nav/tabs.component.html
  src/website/src/app/documentation/demos/tabs/tabs-angular-vertical.demo.html
  src/website/src/app/documentation/demos/tabs/tabs-angular-vertical.ts
  src/website/src/app/documentation/demos/tabs/tabs-static-vertical.demo.html
  src/website/src/app/documentation/demos/tabs/tabs-static-vertical.ts
  src/website/src/app/documentation/demos/tabs/tabs.demo.html
  src/website/src/app/documentation/demos/tabs/tabs.demo.module.ts
Labels: dco-required

#3196 [NG] remove duplicate aria behavior with alerts
  src/clr-angular/emphasis/alert/alert.html
  src/clr-angular/emphasis/alert/alert.spec.ts
Labels: PR Target: Master & Patch

#3211 [NG] Stop caching children for lazy recursive trees
  src/clr-angular/data/tree-view/models/recursive-tree-node.model.spec.ts
  src/clr-angular/data/tree-view/models/recursive-tree-node.model.ts
  src/clr-angular/data/tree-view/recursive-children.spec.ts
  src/clr-angular/data/tree-view/recursive-children.ts
Labels: Bug, Dev

#3192 New icons
  gemini/dark-screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/dark-screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/dark-screens/iconography/selection-technology-shapes/solid/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/line/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-essential-shapes/solid/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/line/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-alerted/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid-badged/chrome.png
  gemini/screens/iconography/selection-technology-shapes/solid/chrome.png
  src/clr-icons/shapes/essential-shapes.ts
  src/clr-icons/shapes/technology-shapes.ts
Labels: Icons, PR Target: Master & Patch

#3227 Fix tree view flickering from async eventemitter
  src/clr-angular/data/tree-view/tree-node.spec.ts
  src/clr-angular/data/tree-view/tree-node.ts
  src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.html
  src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts
  src/dev/src/app/tree-view/pre-selection/pre-selection.html
  src/dev/src/app/tree-view/pre-selection/pre-selection.ts
Labels: PR Target: Master & Patch

#3241 [UI] fix node height inconsistency
  gemini/dark-screens/tree-view/Children pre-selection/default/chrome.png
  gemini/dark-screens/tree-view/Eager declarative tree/default/chrome.png
  gemini/dark-screens/tree-view/Eager recursive tree/default/chrome.png
  gemini/dark-screens/tree-view/Lazy declarative tree/default/chrome.png
  gemini/dark-screens/tree-view/Lazy recursive tree/default/chrome.png
  gemini/dark-screens/tree-view/Pre-selection/default/chrome.png
  gemini/dark-screens/tree-view/Tree with icons/default/chrome.png
  gemini/screens/tree-view/Children pre-selection/default/chrome.png
  gemini/screens/tree-view/Eager declarative tree/default/chrome.png
  gemini/screens/tree-view/Eager recursive tree/default/chrome.png
  gemini/screens/tree-view/Lazy declarative tree/default/chrome.png
  gemini/screens/tree-view/Lazy recursive tree/default/chrome.png
  gemini/screens/tree-view/Pre-selection/default/chrome.png
  gemini/screens/tree-view/Tree with icons/default/chrome.png
  src/clr-angular/data/tree-view/_tree-view.clarity.scss
  src/clr-angular/data/tree-view/_variables.tree-view.scss
Labels: PR Target: Master & Patch
