Repository vmware/clarity, pull requests merged in 2019-07, with the labels that each got.

#3534 [NG] Backport Feature/issue 3464
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.spec.ts
Labels: Accessibility, Backport

#3537 Datagrid focus management (part 2 - show/hide columns)
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-action-overflow.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle-button.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.spec.ts
  src/clr-angular/data/datagrid/datagrid-column-toggle.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Labels: Accessibility, PR Target: Master & Patch

#3532 [NG] fix(signpost): Adds a11y to the signpost
  gemini/dark-screens/signposts/bottom-left/chrome.png
  gemini/dark-screens/signposts/bottom-middle/chrome.png
  gemini/dark-screens/signposts/bottom-right/chrome.png
  gemini/dark-screens/signposts/default/chrome.png
  gemini/dark-screens/signposts/left-bottom/chrome.png
  gemini/dark-screens/signposts/left-middle/chrome.png
  gemini/dark-screens/signposts/left-top/chrome.png
  gemini/dark-screens/signposts/right-bottom/chrome.png
  gemini/dark-screens/signposts/right-middle/chrome.png
  gemini/dark-screens/signposts/right-top/chrome.png
  gemini/dark-screens/signposts/top-left/chrome.png
  gemini/dark-screens/signposts/top-middle/chrome.png
  gemini/dark-screens/signposts/top-right/chrome.png
  gemini/screens/signposts/bottom-left/chrome.png
  gemini/screens/signposts/bottom-middle/chrome.png
  gemini/screens/signposts/bottom-right/chrome.png
  gemini/screens/signposts/default/chrome.png
  gemini/screens/signposts/left-bottom/chrome.png
  gemini/screens/signposts/left-middle/chrome.png
  gemini/screens/signposts/left-top/chrome.png
  gemini/screens/signposts/right-bottom/chrome.png
  gemini/screens/signposts/right-middle/chrome.png
  gemini/screens/signposts/right-top/chrome.png
  gemini/screens/signposts/top-left/chrome.png
  gemini/screens/signposts/top-middle/chrome.png
  gemini/screens/signposts/top-right/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/popover/signpost/_signposts.clarity.scss
  src/clr-angular/popover/signpost/all.spec.ts
  src/clr-angular/popover/signpost/providers/signpost-id.service.spec.ts
  src/clr-angular/popover/signpost/providers/signpost-id.service.ts
  src/clr-angular/popover/signpost/signpost-content.spec.ts
  src/clr-angular/popover/signpost/signpost-content.ts
  src/clr-angular/popover/signpost/signpost-trigger.spec.ts
  src/clr-angular/popover/signpost/signpost-trigger.ts
  src/clr-angular/popover/signpost/signpost.spec.ts
  src/clr-angular/popover/signpost/signpost.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
Labels: Accessibility, PR Target: Master & Patch

#3596 fix(forms) link helper text to input with aria-describedby
  golden/clr-angular.d.ts
  src/clr-angular/forms/common/helper.spec.ts
  src/clr-angular/forms/common/helper.ts
  src/clr-angular/forms/common/wrapped-control.spec.ts
  src/clr-angular/forms/common/wrapped-control.ts
  src/clr-angular/forms/tests/container.spec.ts
Labels: PR Target: Master & Patch

#3605 [WEB] Fix typo in themes.demo.html
  src/website/src/app/documentation/demos/themes/themes.demo.html
Labels: Website

#3555 Icons in buttons need accessible names
  package-lock.json
  src/clr-icons/clr-icons-element.ts
  src/clr-icons/clr-icons.spec.ts
  src/website/src/app/documentation/demos/button-group/button-group.demo.html
  src/website/src/app/documentation/demos/button-group/button-group.demo.ts
  src/website/src/app/documentation/demos/buttons/buttons.demo.html
Labels: Accessibility, PR Target: Master & Patch

#3559 [NG] stepper a11y states
  golden/clr-angular.d.ts
  src/clr-angular/accordion/accordion-panel.html
  src/clr-angular/accordion/accordion-panel.ts
  src/clr-angular/accordion/stepper/models/stepper.model.spec.ts
  src/clr-angular/accordion/stepper/models/stepper.model.ts
  src/clr-angular/accordion/stepper/stepper-panel.spec.ts
  src/clr-angular/accordion/stepper/stepper-panel.ts
Labels: Accessibility

#3613 Backport Icons in buttons need accessible names 3530
  src/clr-icons/clr-icons-element.ts
  src/clr-icons/clr-icons.spec.ts
  src/website/src/app/documentation/demos/button-group/button-group.demo.html
  src/website/src/app/documentation/demos/button-group/button-group.demo.ts
  src/website/src/app/documentation/demos/buttons/buttons.demo.html
Labels: Accessibility, Backport, Ready to Review

#3615 build: adds file formatting script for npm users
  BUILD.md
  package.json
Labels: Build

#3623 fix(forms): describe by for input validation errors
  golden/clr-angular.d.ts
  src/clr-angular/forms/common/error.spec.ts
  src/clr-angular/forms/common/error.ts
  src/clr-angular/forms/common/wrapped-control.spec.ts
  src/clr-angular/forms/common/wrapped-control.ts
Labels: Accessibility

#3625 fix: adding the text-edit set to the svg icon build script
  scripts/clr-icons-svg.js
Labels: Build, Icons

#3493 [NG] Create new component clrSpinner
  golden/clr-angular.d.ts
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.module.ts
  src/clr-angular/index.ts
  src/clr-angular/progress/spinner/_spinner.clarity.scss
  src/clr-angular/progress/spinner/index.ts
  src/clr-angular/progress/spinner/spinner.module.ts
  src/clr-angular/progress/spinner/spinner.spec.ts
  src/clr-angular/progress/spinner/spinner.ts
  src/clr-angular/utils/component/is-boolean-attribute-set.spec.ts
  src/clr-angular/utils/component/is-boolean-attribute-set.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/ks-app/src/app/containers/spinners/spinners.component.html
  src/ks-app/src/app/containers/wizard/wizards.component.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
  src/website/src/app/documentation/demos/spinners/spinner-component.html
  src/website/src/app/documentation/demos/spinners/spinner-component.ts
  src/website/src/app/documentation/demos/spinners/spinner.demo.html
  src/website/src/app/documentation/demos/spinners/spinner.demo.scss
  src/website/src/app/documentation/demos/spinners/spinners.demo.module.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
  src/website/src/settings/componentlist.json
Labels: Accessibility, New Component, PR Target: Master & Patch, Ready to Review

#3584 fix(login) the login screen was missing labels for form fields
  src/dev/src/app/login/login.demo.html
  src/website/src/app/documentation/demos/login/login-example.demo.html
  src/website/src/app/documentation/demos/login/login-example.demo.ts
  src/website/src/app/documentation/demos/login/login.demo.html
Labels: PR Target: Master & Patch

#3606 [UI] Update line-height for clr-control-label
  gemini/dark-screens/checkboxes/default/chrome.png
  gemini/dark-screens/datepicker/layout/default/chrome.png
  gemini/dark-screens/forms/form-checkbox/default/chrome.png
  gemini/dark-screens/forms/form-file/default/chrome.png
  gemini/dark-screens/forms/form-horizontal-angular/default/chrome.png
  gemini/dark-screens/forms/form-horizontal-grid/default/chrome.png
  gemini/dark-screens/forms/form-horizontal/default/chrome.png
  gemini/dark-screens/forms/form-radio/default/chrome.png
  gemini/dark-screens/input/default/chrome.png
  gemini/dark-screens/password/default/chrome.png
  gemini/dark-screens/radios/default/chrome.png
  gemini/dark-screens/selects/default/chrome.png
  gemini/dark-screens/textarea/default/chrome.png
  gemini/dark-screens/toggles/default/chrome.png
  gemini/screens/checkboxes/default/chrome.png
  gemini/screens/datepicker/layout/default/chrome.png
  gemini/screens/forms/form-checkbox/default/chrome.png
  gemini/screens/forms/form-file/default/chrome.png
  gemini/screens/forms/form-horizontal-angular/default/chrome.png
  gemini/screens/forms/form-horizontal-grid/default/chrome.png
  gemini/screens/forms/form-horizontal/default/chrome.png
  gemini/screens/forms/form-radio/default/chrome.png
  gemini/screens/input/default/chrome.png
  gemini/screens/password/default/chrome.png
  gemini/screens/radios/default/chrome.png
  gemini/screens/selects/default/chrome.png
  gemini/screens/textarea/default/chrome.png
  gemini/screens/toggles/default/chrome.png
  src/clr-angular/forms/styles/_containers.clarity.scss
  src/clr-angular/forms/styles/containers.spec.ts
Labels: It's Not You It's Me, PR Target: Master & Patch, Ready to Review, Website

#3636 fix(ng): dropdown item should add disabled attribute if set by input
  src/clr-angular/popover/dropdown/dropdown-item.spec.ts
  src/clr-angular/popover/dropdown/dropdown-item.ts
Labels: Regression

#3626 fix(stepper): remove interstitial content
  gemini/dark-screens/accordion/default/chrome.png
  gemini/dark-screens/stepper/default/chrome.png
  gemini/screens/accordion/default/chrome.png
  gemini/screens/stepper/default/chrome.png
  golden/clr-angular.d.ts
  src/clr-angular/accordion/_accordion.clarity.scss
  src/clr-angular/accordion/accordion-panel.html
  src/clr-angular/accordion/accordion-panel.spec.ts
  src/clr-angular/accordion/accordion-panel.ts
  src/dev/src/app/accordion/accordion.demo.html
  src/dev/src/app/stepper/stepper.demo.html
Labels: Accessibility

#3631 Fix/clr spinner
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/progress/spinner/spinner.spec.ts
  src/clr-angular/progress/spinner/spinner.ts
  src/dev/src/app/spinners/spinner-component.html
  src/dev/src/app/spinners/spinner-component.ts
  src/dev/src/app/spinners/spinner.demo.ts
  src/dev/src/app/spinners/spinners.demo.module.ts
  src/dev/src/app/spinners/spinners.demo.routing.ts
  src/website/src/app/documentation/demos/spinners/spinner-component.html
  src/website/src/app/documentation/demos/spinners/spinner-component.ts
  src/website/src/app/documentation/demos/spinners/spinner.demo.html
Labels: Accessibility, Ready to Review

#3629 feat(clrSpinner): adding new component clrSpinner - Backport to v1
  golden/clr-angular.d.ts
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.module.ts
  src/clr-angular/index.ts
  src/clr-angular/progress/spinner/_spinner.clarity.scss
  src/clr-angular/progress/spinner/index.ts
  src/clr-angular/progress/spinner/spinner.module.ts
  src/clr-angular/progress/spinner/spinner.spec.ts
  src/clr-angular/progress/spinner/spinner.ts
  src/clr-angular/utils/component/is-boolean-attribute-set.spec.ts
  src/clr-angular/utils/component/is-boolean-attribute-set.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/dev/src/app/spinners/spinner-component.html
  src/dev/src/app/spinners/spinner-component.ts
  src/dev/src/app/spinners/spinner.demo.ts
  src/dev/src/app/spinners/spinners.demo.module.ts
  src/dev/src/app/spinners/spinners.demo.routing.ts
  src/ks-app/src/app/containers/spinners/spinners.component.html
  src/ks-app/src/app/containers/wizard/wizards.component.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
  src/website/src/app/documentation/demos/spinners/spinner-component.html
  src/website/src/app/documentation/demos/spinners/spinner-component.ts
  src/website/src/app/documentation/demos/spinners/spinner.demo.html
  src/website/src/app/documentation/demos/spinners/spinner.demo.scss
  src/website/src/app/documentation/demos/spinners/spinners.demo.module.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
  src/website/src/settings/componentlist.json
Labels: Accessibility, Backport, Ready to Review

#3506 [NG] adding labels to Datagrid single & expandable column
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid.html
  src/clr-angular/data/datagrid/datagrid.spec.ts
  src/clr-angular/data/datagrid/datagrid.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/clr-angular/utils/i18n/common-strings.service.ts
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Labels: Accessibility, PR Target: Master & Patch

#3533 [NG] Init clrProgressBar Component
  golden/clr-angular.d.ts
  src/clr-angular/clr-angular.module.ts
  src/clr-angular/index.ts
  src/clr-angular/progress/progress-bars/index.ts
  src/clr-angular/progress/progress-bars/progress-bar.module.ts
  src/clr-angular/progress/progress-bars/progress-bar.spec.ts
  src/clr-angular/progress/progress-bars/progress-bar.ts
  src/dev/src/app/progress-bars/progress-bar-component.html
  src/dev/src/app/progress-bars/progress-bar-component.ts
  src/dev/src/app/progress-bars/progress-bars.demo.module.ts
  src/dev/src/app/progress-bars/progress-bars.demo.routing.ts
  src/dev/src/app/progress-bars/progress-bars.demo.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bar-component.demo.html
  src/website/src/app/documentation/demos/progress-bars/progress-bar-component.demo.ts
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.html
  src/website/src/app/documentation/demos/progress-bars/progress-bars.demo.module.ts
  src/website/src/settings/componentlist.json
Labels: Accessibility, New Component, PR Target: Master & Patch, Ready to Review

#3651 fix(wizard): prevent closing non closable wizards
  src/clr-angular/wizard/wizard.spec.ts
  src/clr-angular/wizard/wizard.ts
Labels: Accessibility, PR Target: Master & Patch
