Repository vmware/clarity, pull requests merged in 2019-08, with the labels that each got.

#3657 fix(modal): tab focus style
  src/clr-angular/modal/modal-body.spec.ts
  src/clr-angular/modal/modal-body.ts
Labels: Accessibility, PR Target: Master & Patch

#3599 [WEB] Bug/3505
  src/clr-angular/utils/_helpers.clarity.scss
  src/website/src/app/documentation/demos/datagrid/expandable-rows/expandable-rows.html
  src/website/src/app/documentation/demos/datagrid/expandable-rows/expandable-rows.ts
  src/website/src/app/documentation/demos/datagrid/filtering/examples.ts
  src/website/src/app/documentation/demos/datagrid/filtering/filtering.html
  src/website/src/app/documentation/demos/datagrid/utils/pokemon-comparator.ts
Labels: Bug, Website

#3662 feat: add aria-label for alert close button
  golden/clr-angular.d.ts
  src/clr-angular/emphasis/alert/alert.html
  src/clr-angular/emphasis/alert/alert.spec.ts
  src/clr-angular/emphasis/alert/alert.ts
  src/clr-angular/utils/i18n/common-strings.default.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/website/src/app/documentation/demos/alert/alerts.demo.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-completion.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.html
  src/website/src/app/documentation/demos/wizard/wizard-async-validation.demo.ts
  src/website/src/app/documentation/demos/wizard/wizard-design.demo.html
Labels: Accessibility, PR Target: Master & Patch, Ready to Review, Website

#3674 fix: line-height for v1 .clr-control-label
  gemini/dark-screens/checkboxes/default/chrome.png
  gemini/dark-screens/datepicker/layout/default/chrome.png
  gemini/dark-screens/forms/form-checkbox/default/chrome.png
  gemini/dark-screens/forms/form-compact-angular/default/chrome.png
  gemini/dark-screens/forms/form-compact-grid/default/chrome.png
  gemini/dark-screens/forms/form-compact/default/chrome.png
  gemini/dark-screens/forms/form-file/default/chrome.png
  gemini/dark-screens/forms/form-horizontal-angular/default/chrome.png
  gemini/dark-screens/forms/form-horizontal-grid/default/chrome.png
  gemini/dark-screens/forms/form-horizontal/default/chrome.png
  gemini/dark-screens/forms/form-input-group/default/chrome.png
  gemini/dark-screens/forms/form-radio/default/chrome.png
  gemini/dark-screens/forms/form-select/default/chrome.png
  gemini/dark-screens/forms/form-text/default/chrome.png
  gemini/dark-screens/forms/form-textarea/default/chrome.png
  gemini/dark-screens/forms/form-vertical-angular/default/chrome.png
  gemini/dark-screens/forms/form-vertical-grid/default/chrome.png
  gemini/dark-screens/forms/form-vertical/default/chrome.png
  gemini/dark-screens/input/default/chrome.png
  gemini/dark-screens/login/layout/default/chrome.png
  gemini/dark-screens/password/default/chrome.png
  gemini/dark-screens/radios/default/chrome.png
  gemini/dark-screens/selects/default/chrome.png
  gemini/dark-screens/textarea/default/chrome.png
  gemini/dark-screens/toggles/default/chrome.png
  gemini/screens/checkboxes/default/chrome.png
  gemini/screens/datepicker/layout/default/chrome.png
  gemini/screens/forms/form-checkbox/default/chrome.png
  gemini/screens/forms/form-compact-angular/default/chrome.png
  gemini/screens/forms/form-compact-grid/default/chrome.png
  gemini/screens/forms/form-compact/default/chrome.png
  gemini/screens/forms/form-file/default/chrome.png
  gemini/screens/forms/form-horizontal-angular/default/chrome.png
  gemini/screens/forms/form-horizontal-grid/default/chrome.png
  gemini/screens/forms/form-horizontal/default/chrome.png
  gemini/screens/forms/form-input-group/default/chrome.png
  gemini/screens/forms/form-radio/default/chrome.png
  gemini/screens/forms/form-select/default/chrome.png
  gemini/screens/forms/form-text/default/chrome.png
  gemini/screens/forms/form-textarea/default/chrome.png
  gemini/screens/forms/form-vertical-angular/default/chrome.png
  gemini/screens/forms/form-vertical-grid/default/chrome.png
  gemini/screens/forms/form-vertical/default/chrome.png
  gemini/screens/input/default/chrome.png
  gemini/screens/login/layout/default/chrome.png
  gemini/screens/password/default/chrome.png
  gemini/screens/radios/default/chrome.png
  gemini/screens/selects/default/chrome.png
  gemini/screens/textarea/default/chrome.png
  gemini/screens/toggles/default/chrome.png
  src/clr-angular/forms/styles/_containers.clarity.scss
  src/clr-angular/forms/styles/containers.spec.ts
Labels: Bug

#3691 chore: delete unused ssr code
  package.json
  src/website/karma.conf.js
  src/website/prerender.ts
  src/website/server.ts
  src/website/src/main.server.ts
  src/website/tsconfig.app.json
  src/website/tsconfig.server.json
  src/website/tsconfig.spec.json
  src/website/webpack.server.config.js
Labels: Build, Chore

#3632 fix(datepicker): adds aria-labels for buttons
  golden/clr-angular.d.ts
  src/clr-angular/forms/datepicker/all.spec.ts
  src/clr-angular/forms/datepicker/date-container.spec.ts
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/forms/datepicker/datepicker-view-manager.spec.ts
  src/clr-angular/forms/datepicker/datepicker-view-manager.ts
  src/clr-angular/forms/datepicker/day.spec.ts
  src/clr-angular/forms/datepicker/day.ts
  src/clr-angular/forms/datepicker/daypicker.html
  src/clr-angular/forms/datepicker/daypicker.spec.ts
  src/clr-angular/forms/datepicker/daypicker.ts
  src/clr-angular/forms/datepicker/model/day.model.spec.ts
  src/clr-angular/forms/datepicker/model/day.model.ts
  src/clr-angular/forms/datepicker/monthpicker.spec.ts
  src/clr-angular/forms/datepicker/yearpicker.spec.ts
  src/clr-angular/forms/datepicker/yearpicker.ts
  src/clr-angular/utils/i18n/common-strings.default.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/dev/src/app/datepicker/datepicker.demo.module.ts
  src/website/src/app/documentation/demos/i18n/i18n.demo.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
Labels: Accessibility, PR Target: Master & Patch, Ready to Review

#3676 fix: alerts in wizzard are read immediately when not urgent
  golden/clr-angular.d.ts
  src/clr-angular/emphasis/alert/alert.html
  src/clr-angular/emphasis/alert/alert.spec.ts
  src/clr-angular/emphasis/alert/alert.ts
  src/dev/src/app/wizard/wizard-async-validation.demo.html
  src/website/src/app/documentation/demos/alert/alerts.demo.html
Labels: Accessibility

#3682 fix: improve screen reader behaviors on stack-view and modal
  gemini/dark-screens/modal/max-height/default/chrome.png
  gemini/screens/modal/max-height/default/chrome.png
  golden/clr-angular.d.ts
  package-lock.json
  src/clr-angular/data/stack-view/all.spec.ts
  src/clr-angular/data/stack-view/stack-block.spec.ts
  src/clr-angular/data/stack-view/stack-block.ts
  src/clr-angular/data/stack-view/stack-content-input.spec.ts
  src/clr-angular/data/stack-view/stack-content-input.ts
  src/clr-angular/data/stack-view/stack-view.module.ts
  src/clr-angular/modal/_modal.clarity.scss
  src/clr-angular/modal/modal.html
  src/clr-angular/modal/modal.spec.ts
  src/clr-angular/modal/modal.ts
  src/clr-angular/utils/i18n/common-strings.default.ts
  src/clr-angular/utils/i18n/common-strings.interface.ts
  src/dev/src/app/stack-view/stack-view-angular-modal-edit.html
  src/website/src/app/documentation/demos/i18n/i18n.demo.ts
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.html
Labels: PR Target: Master & Patch

#3700 Topic/key focus
  gemini/dark-screens/tabs/angular/default/chrome.png
  gemini/dark-screens/tabs/angular/overflowing/chrome.png
  gemini/dark-screens/tabs/angular/vertical-hover/chrome.png
  gemini/screens/tabs/angular/default/chrome.png
  gemini/screens/tabs/angular/overflowing/chrome.png
  gemini/screens/tabs/angular/vertical-hover/chrome.png
  gemini/tests/set4/tabs.js
  golden/clr-angular.d.ts
  src/clr-angular/layout/tabs/_tabs.clarity.scss
  src/clr-angular/layout/tabs/tab-link.directive.ts
  src/clr-angular/layout/tabs/tabs.module.ts
  src/clr-angular/layout/tabs/tabs.spec.ts
  src/clr-angular/layout/tabs/tabs.ts
  src/clr-angular/utils/focus/key-codes.enum.ts
  src/clr-angular/utils/focus/key-focus/enums/focus-direction.enum.ts
  src/clr-angular/utils/focus/key-focus/index.ts
  src/clr-angular/utils/focus/key-focus/interfaces.ts
  src/clr-angular/utils/focus/key-focus/key-focus-item.spec.ts
  src/clr-angular/utils/focus/key-focus/key-focus-item.ts
  src/clr-angular/utils/focus/key-focus/key-focus.module.ts
  src/clr-angular/utils/focus/key-focus/key-focus.spec.ts
  src/clr-angular/utils/focus/key-focus/key-focus.ts
  src/clr-angular/utils/focus/key-focus/util.spec.ts
  src/clr-angular/utils/focus/key-focus/util.ts
  src/dev/src/app/tabs/tabs-angular.demo.html
  src/dev/src/app/tabs/tabs.demo.module.ts
Labels: Accessibility, PR Target: Master & Patch

#3714 bug(modal): clrModalOpenChange was fired more than once when closing
  src/clr-angular/modal/modal.spec.ts
  src/clr-angular/modal/modal.ts
Labels: PR Target: Master & Patch, type: bug

#3736 fix(datagrid): fix hsl regression
  src/clr-angular/data/datagrid/_variables.datagrid.scss
Labels: Regression

#3697 docs(header): header have buttons without accessible names #3518
  src/website/src/app/documentation/demos/header/header-links.demo.html
  src/website/src/app/documentation/demos/header/header-links.ts
  src/website/src/app/documentation/demos/header/header-types.demo.html
  src/website/src/app/documentation/demos/header/header-types.ts
  src/website/src/app/documentation/demos/header/header.demo.html
  src/website/src/app/documentation/demos/header/sub-nav.demo.html
Labels: Accessibility, PR Target: Master & Patch, type: website

#3706 fix(dropdown): handle error when there are no items in dropdown to focus
  src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
  src/clr-angular/utils/focus/focus.service.spec.ts
  src/clr-angular/utils/focus/focus.service.ts
Labels: type: bug

#3753 backport fix(dropdown): handle focus first item when there is non selectable item
  src/clr-angular/popover/dropdown/providers/dropdown-focus-handler.service.ts
  src/clr-angular/utils/focus/focus.service.spec.ts
  src/clr-angular/utils/focus/focus.service.ts
Labels: Backport, type: bug
