Repository vmware/clarity, pull requests merged in 2020-01, with the labels that each got.

#4121 feat(datalist): add datalist component
  commitlint.config.js
  gemini/dark-screens/datalist/default/chrome.png
  gemini/dark-screens/landing-page/default/chrome.png
  gemini/dark-screens/landing-page/setting-clicked/chrome.png
  gemini/dark-screens/landing-page/setting-hovered/chrome.png
  gemini/dark-screens/landing-page/sidenav-hovered/chrome.png
  gemini/dark-screens/wizard/basic/default/chrome.png
  gemini/dark-screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/dark-screens/wizard/static-wizard/default/chrome.png
  gemini/screens/datalist/default/chrome.png
  gemini/screens/landing-page/default/chrome.png
  gemini/screens/landing-page/setting-clicked/chrome.png
  gemini/screens/landing-page/setting-hovered/chrome.png
  gemini/screens/landing-page/sidenav-hovered/chrome.png
  gemini/screens/wizard/basic/default/chrome.png
  gemini/screens/wizard/static-wizard-shortcontent/default/chrome.png
  gemini/screens/wizard/static-wizard/default/chrome.png
  gemini/tests/set2/datalist.js
  golden/clr-angular.d.ts
  src/clr-angular/forms/datalist/all.spec.ts
  src/clr-angular/forms/datalist/datalist-container.spec.ts
  src/clr-angular/forms/datalist/datalist-container.ts
  src/clr-angular/forms/datalist/datalist-input.spec.ts
  src/clr-angular/forms/datalist/datalist-input.ts
  src/clr-angular/forms/datalist/datalist.module.ts
  src/clr-angular/forms/datalist/datalist.spec.ts
  src/clr-angular/forms/datalist/datalist.ts
  src/clr-angular/forms/datalist/index.ts
  src/clr-angular/forms/datalist/providers/datalist-id.service.spec.ts
  src/clr-angular/forms/datalist/providers/datalist-id.service.ts
  src/clr-angular/forms/forms.module.ts
  src/clr-angular/forms/index.ts
  src/clr-angular/forms/styles/_datalist.clarity.scss
  src/clr-angular/forms/tests/container.spec.ts
  src/clr-angular/forms/tests/control.spec.ts
  src/clr-angular/utils/_components.clarity.scss
  src/dev/src/app/app.routing.ts
  src/dev/src/app/datalist/datalist.demo.html
  src/dev/src/app/datalist/datalist.demo.module.ts
  src/dev/src/app/datalist/datalist.demo.routing.ts
  src/dev/src/app/datalist/datalist.demo.ts
  src/website/src/app/documentation/demos/datalist/datalist-basic.demo.html
  src/website/src/app/documentation/demos/datalist/datalist-basic.demo.ts
  src/website/src/app/documentation/demos/datalist/datalist-reactive-validation.demo.html
  src/website/src/app/documentation/demos/datalist/datalist-reactive-validation.demo.ts
  src/website/src/app/documentation/demos/datalist/datalist-template-validation.demo.html
  src/website/src/app/documentation/demos/datalist/datalist-template-validation.demo.ts
  src/website/src/app/documentation/demos/datalist/datalist.demo.html
  src/website/src/app/documentation/demos/datalist/datalist.demo.ts
  src/website/src/app/documentation/demos/datalist/datalist.module.ts
  src/website/src/app/documentation/documentation-routing.module.ts
  src/website/src/settings/componentlist.json
Labels: target: master

#4145 fix(datagrid): datagrid-row add aria-expanded & aria-label on open/close
  src/clr-angular/data/datagrid/datagrid-row.html
  src/clr-angular/data/datagrid/datagrid-row.spec.ts
  src/clr-angular/data/datagrid/datagrid-row.ts
Labels: component: datagrid, type: bug

#4153 feat(icons): migrating chart icon set to clr-core
  src/clr-core/icon-shapes/collections/chart.ts
  src/clr-core/icon-shapes/index.ts
  src/clr-core/icon-shapes/shapes/axis-chart.ts
  src/clr-core/icon-shapes/shapes/bar-chart.ts
  src/clr-core/icon-shapes/shapes/bell-curve.ts
  src/clr-core/icon-shapes/shapes/box-plot.ts
  src/clr-core/icon-shapes/shapes/bubble-chart.ts
  src/clr-core/icon-shapes/shapes/cloud-chart.ts
  src/clr-core/icon-shapes/shapes/curve-chart.ts
  src/clr-core/icon-shapes/shapes/grid-chart.ts
  src/clr-core/icon-shapes/shapes/heat-map.ts
  src/clr-core/icon-shapes/shapes/line-chart.ts
  src/clr-core/icon-shapes/shapes/pie-chart.ts
  src/clr-core/icon-shapes/shapes/scatter-plot.ts
  src/clr-core/icon-shapes/shapes/tick-chart.ts
  src/dev-core/src/app/icon-sets/icon-sets.demo.ts
Labels: BLOCKED

#4131 Fix(datagrid): The Select All checkbox has some position mis-alignment issue in multiple options of datagrid
  src/clr-angular/data/datagrid/datagrid.html
Labels: component: datagrid, target: n-1 or n-2, type: bug

#4159 chore(build): run api documentation only when there is a change
  package-lock.json
  package.json
Labels: type: build

#4175 fix(a11y): service ClrCommonStringsService initialize twice at run-time
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/popover/signpost/signpost-content.ts
Labels: type: bug

#4174 fix(date-picker): set disabled state without the need of clrForm
  golden/clr-angular.d.ts
  src/clr-angular/forms/datepicker/date-container.spec.ts
  src/clr-angular/forms/datepicker/date-container.ts
  src/clr-angular/forms/datepicker/date-input.ts
  src/clr-angular/forms/datepicker/providers/date-form-control.service.ts
  src/dev/src/app/datepicker/disabled.html
  src/dev/src/app/datepicker/disabled.ts
Labels: component: date-picker, target: master & n-1, type: bug

#4142 feat(stack-view): a11y aria-level, aria-posinset and aria-setsize
  golden/clr-angular.d.ts
  src/clr-angular/data/stack-view/stack-block.spec.ts
  src/clr-angular/data/stack-view/stack-block.ts
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-basic.html
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-basic.ts
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.html
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-lazyload.ts
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.html
  src/website/src/app/documentation/demos/stack-view/stack-view-angular-modal-edit.ts
  src/website/src/app/documentation/demos/stack-view/stack-view-static.html
  src/website/src/app/documentation/demos/stack-view/stack-view-static.ts
  src/website/src/app/documentation/demos/stack-view/stack-view.demo.html
Labels: component: stack view, target: master & n-1, type: accessibility

#4151 feat: update the limit of header-max-length from 72 to 100 characters
  commitlint.config.js
Labels: type: build

#4198 fix(datalist): adds optional service
  gemini/dark-screens/datalist/default/chrome.png
  gemini/screens/datalist/default/chrome.png
  src/clr-angular/forms/datalist/datalist.spec.ts
  src/clr-angular/forms/datalist/datalist.ts
  src/dev/src/app/datalist/datalist.demo.html
Labels: target: master

#4224 fix(date-picker): guard calling an optional date picker service
  golden/clr-angular.d.ts
  src/clr-angular/button/button-group/button-group.ts
  src/clr-angular/forms/datepicker/date-input.spec.ts
  src/clr-angular/forms/datepicker/date-input.ts
Labels: target: master & n-1

#4180 fix(datagrid): update single action close behavior
  golden/clr-angular.d.ts
  src/clr-angular/data/datagrid/datagrid-action-overflow.spec.ts
  src/clr-angular/data/datagrid/datagrid-action-overflow.ts
Labels: target: master & n-1
