Repository vmware/clarity, pull requests merged in 2021-08, with the labels that each got.

#6201 feat(adoption): add input demos
  src/app/migrations/input/input.1.angular.txt
  src/app/migrations/input/input.1.core.txt
  src/app/migrations/input/input.2.angular.txt
  src/app/migrations/input/input.2.core.txt
  src/app/migrations/input/input.3.angular.txt
  src/app/migrations/input/input.3.core.txt
  src/app/migrations/input/input.4.angular.txt
  src/app/migrations/input/input.4.core.txt
  src/app/pages/input.page.ts
  src/app/templates/angular.angular.json.txt
  src/app/templates/angular.app.module.ts.txt
  src/app/templates/core.app.module.ts.txt
Labels: Adoption

#6205 feat(adoption:modal) adding modal example
  src/app/components/demo.component.ts
  src/app/migrations/modal/modal.1.angular.txt
  src/app/migrations/modal/modal.1.core.txt
  src/app/migrations/modal/modal.2.angular.txt
  src/app/migrations/modal/modal.2.core.txt
  src/app/pages/modal.page.ts
Labels: Adoption, Documentation

#6203 fix(core:control): label alignments
  packages/core/src/forms/control-group/control-group.element.scss
  packages/core/src/forms/control/control.element.scss
  packages/core/src/input/input-groups.stories.ts
  packages/core/web-dev-server.config.mjs
Labels: @cds/core

#6202 build: refactoring visual-diff tool and covering core stories with it
  tools/visual-tester/README.md
  tools/visual-tester/__tests__/core.stories.vspec.ts
  tools/visual-tester/__tests__/storybook.vspec.ts
  tools/visual-tester/__tests__/website.vspec.ts
  tools/visual-tester/package.json
  tools/visual-tester/specs/angular.dev.vspec.js
  tools/visual-tester/specs/core.badge.vspec.js
  tools/visual-tester/specs/core.button.vspec.js
  tools/visual-tester/specs/core.foundations.vspec.js
  tools/visual-tester/specs/core.layout.vspec.js
  tools/visual-tester/specs/core.table.vspec.js
  tools/visual-tester/specs/core/stories.vspec.js
  tools/visual-tester/specs/website.vspec.js
  tools/visual-tester/src/runner/context.ts
  tools/visual-tester/src/runner/index.ts
  tools/visual-tester/src/runner/reporters/specReporter.ts
  yarn.lock
Labels: type: build

#6232 feat(angular): angular styles for core integration
  projects/angular/src/utils/_normalize.scss
Labels: @clr/ui, v5, type: backport

#6229 feat(adoption:list): add list demos
  src/app/migrations/list/list.1.angular.txt
  src/app/migrations/list/list.1.core.txt
  src/app/migrations/list/list.2.angular.txt
  src/app/migrations/list/list.2.core.txt
  src/app/migrations/list/list.3.angular.txt
  src/app/migrations/list/list.3.core.txt
  src/app/pages/list.page.ts
Labels: Adoption

#6228 feat(adoption:toggle): add toggle examples
  src/app/migrations/toggle/toggle.1.angular.txt
  src/app/migrations/toggle/toggle.1.core.txt
  src/app/migrations/toggle/toggle.2.angular.txt
  src/app/migrations/toggle/toggle.2.core.txt
  src/app/migrations/toggle/toggle.3.angular.txt
  src/app/migrations/toggle/toggle.3.core.txt
  src/app/pages/toggle.page.ts
Labels: Adoption

#6241 feat(adoption): add pages for all components clarity has
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/pages/combobox.page.ts
  src/app/pages/dropdown.page.ts
  src/app/pages/header.page.ts
  src/app/pages/progressbar.page.ts
  src/app/pages/signpost.page.ts
  src/app/pages/spinner.page.ts
  src/app/pages/stackview.page.ts
  src/app/pages/stepper.page.ts
  src/app/pages/tab.page.ts
  src/app/pages/table.page.ts
  src/app/pages/timeline.page.ts
  src/app/pages/tooltip.page.ts
  src/app/pages/treeview.page.ts
  src/app/pages/wizard.page.ts
Labels: Adoption

#6226 fix(website): changelog message format alignment
  changelogs/v5.json
Labels: type: website

#6240 Small typo "ach" -> "Each"
  apps/website/angular-components/tab/README.md
Labels: dco-required, type: website

#6247 Adoption fixes
  src/app/migrations/alert/alert.1.core.txt
  src/app/migrations/alert/alert.2.core.txt
  src/app/migrations/alert/alert.3.core.txt
  src/app/migrations/badges/badge.1.angular.txt
  src/app/migrations/badges/badge.1.core.txt
  src/app/migrations/badges/badge.2.angular.txt
  src/app/migrations/badges/badge.2.core.txt
  src/app/migrations/card/card.1.core.txt
  src/app/migrations/card/card.2.core.txt
  src/app/migrations/checkbox/checkbox.1.angular.txt
  src/app/migrations/checkbox/checkbox.1.core.txt
  src/app/migrations/checkbox/checkbox.2.core.txt
  src/app/migrations/datalist/datalist.1.angular.txt
  src/app/migrations/datalist/datalist.1.core.txt
  src/app/migrations/datalist/datalist.2.angular.txt
  src/app/migrations/datalist/datalist.2.core.txt
  src/app/migrations/labels/label.0.core.txt
  src/app/migrations/labels/label.1.angular.txt
  src/app/migrations/labels/label.1.core.txt
  src/app/migrations/labels/label.2.core.txt
  src/app/migrations/labels/label.3.core.txt
  src/app/migrations/labels/label.4.core.txt
  src/app/migrations/list/list.1.core.txt
  src/app/migrations/modal/modal.1.core.txt
  src/app/migrations/modal/modal.2.core.txt
  src/app/migrations/range/range.1.core.txt
  src/app/migrations/select/select.1.core.txt
  src/app/migrations/textarea/textarea.1.core.txt
  src/app/migrations/toggle/toggle.1.angular.txt
  src/app/migrations/toggle/toggle.2.angular.txt
  src/app/migrations/toggle/toggle.2.core.txt
  src/app/migrations/toggle/toggle.3.angular.txt
  src/app/pages/accordion.page.ts
  src/app/pages/badge.page.ts
  src/app/pages/button.page.ts
  src/app/pages/toggle.page.ts
Labels: Adoption

#6218 feat(adoption:password): add password examples
  src/app/migrations/password/password.1.angular.txt
  src/app/migrations/password/password.1.core.txt
  src/app/migrations/password/password.2.angular.txt
  src/app/migrations/password/password.2.core.txt
  src/app/pages/password.page.ts
Labels: Adoption

#6208 Adoption Guide - Range, Select and Textarea
  src/app/migrations/range/range.1.angular.txt
  src/app/migrations/range/range.2.angular.txt
  src/app/migrations/range/range.2.core.txt
  src/app/migrations/select/select.1.angular.txt
  src/app/migrations/select/select.2.angular.txt
  src/app/migrations/select/select.2.core.txt
  src/app/migrations/textarea/textarea.1.angular.txt
  src/app/migrations/textarea/textarea.2.angular.txt
  src/app/migrations/textarea/textarea.2.core.txt
  src/app/pages/range.page.ts
  src/app/pages/select.page.ts
  src/app/pages/textarea.page.ts
Labels: Adoption

#6259 Getting v5 website building and deploying to netlify
  .github/workflows/build.yml
  .github/workflows/dev.yml
  .github/workflows/website.yml
  package.json
  scripts/dev.sh
  scripts/netlify-build.sh
  scripts/website.sh
Labels: type: website, type: build

#6265 feat(adoption): update not-ready page content for components in progress
  src/app/app-routing.module.ts
  src/app/components/not-ready.component.ts
  src/app/pages/progressbar.page.ts
  src/app/pages/signpost.page.ts
  src/app/pages/spinner.page.ts
  src/app/pages/tab.page.ts
  src/app/pages/treeview.page.ts
  src/app/pages/wizard.page.ts
Labels: Adoption

#6266 feat(adoption): form documentation
  src/app/components/demo.component.ts
  src/app/migrations/forms/forms.1.angular.txt
  src/app/migrations/forms/forms.1.core.txt
  src/app/migrations/forms/forms.2.angular.txt
  src/app/migrations/forms/forms.2.core.txt
  src/app/migrations/forms/forms.3.angular.txt
  src/app/migrations/forms/forms.3.core.txt
  src/app/migrations/forms/forms.4.core.txt
  src/app/pages/form.page.ts
Labels: Adoption

#6210 a11y(core:navigation): a change set that improves accessibility for navigation
  .github/workflows/build.yml
  demos/angular/dist/angular/3rdpartylicenses.txt
  demos/angular/dist/angular/767.172aa459320bfd3a352b.js
  demos/angular/dist/angular/ClarityCity-Light.8ecf68418a20cf6e18d2.woff
  demos/angular/dist/angular/ClarityCity-Light.baabe0e5bef12019df15.woff2
  demos/angular/dist/angular/ClarityCity-Medium.5fe7255d99bcac96cf09.woff2
  demos/angular/dist/angular/ClarityCity-Medium.fd2d4c254adaf49d4b4c.woff
  demos/angular/dist/angular/ClarityCity-Regular.61d25f87d971cb452456.woff
  demos/angular/dist/angular/ClarityCity-Regular.7f3f0d7447ea1c59ab46.woff2
  demos/angular/dist/angular/ClarityCity-SemiBold.508f08b507bb08382c2e.woff2
  demos/angular/dist/angular/ClarityCity-SemiBold.ee52c31aeb15041346ab.woff
  demos/angular/dist/angular/favicon.ico
  demos/angular/dist/angular/index.html
  demos/angular/dist/angular/main.ebd1fabb827b882a3fb6.js
  demos/angular/dist/angular/polyfills.6b43fdea2e6c374ca1e8.js
  demos/angular/dist/angular/runtime.b87cc23d8697b130460a.js
  demos/angular/dist/angular/styles.725ae7437a8cac179b94.css
  packages/core/npm.json
  packages/core/src/navigation/navigation-group.element.spec.ts
  packages/core/src/navigation/navigation-group.element.ts
  packages/core/src/navigation/navigation-item.element.scss
  packages/core/src/navigation/navigation-item.element.spec.ts
  packages/core/src/navigation/navigation-item.element.ts
  packages/core/src/navigation/navigation-start.element.scss
  packages/core/src/navigation/navigation-start.element.ts
  packages/core/src/navigation/navigation.element.scss
  packages/core/src/navigation/navigation.element.spec.ts
  packages/core/src/navigation/navigation.element.ts
  packages/core/src/navigation/navigation.stories.ts
  packages/core/src/navigation/utils/index.ts
  packages/core/src/styles/tokens/tokens.stories.ts
Labels: navigation

#6284 feat(react:visual-checkbox): adding visual checkbox react wrapper
  packages/react/App.tsx
  packages/react/index.tsx
  packages/react/package.json
  packages/react/src/visual-checkbox/__snapshots__/index.test.tsx.snap
  packages/react/src/visual-checkbox/entrypoint.tsconfig.json
  packages/react/src/visual-checkbox/index.test.tsx
  packages/react/src/visual-checkbox/index.tsx
  packages/react/src/visual-checkbox/package.json
  yarn.lock
Labels: @cds/react

#6297 fix(angular): rework the cds-angular build to use the new custom-elements json format
  packages/angular/projects/cds-angular/src/all.spec.ts
  packages/core/rollup.utils.js
  packages/core/src/forms/control-action/control-action.element.ts
  packages/core/src/forms/control-inline/control-inline.element.ts
  packages/core/src/forms/control-label/control-label.element.ts
  scripts/core-ng-module-generator.js
Labels: @cds/angular
